import React,{useCallback,useEffect,useRef,useState} from 'react';
import {GameContainer} from '../ui/game/GamePrimitives';
import {evaluateAkari} from '../../lib/games/logic-puzzles';
import {createLightUp,explainLightUpHint,hintLightUp,LIGHT_UP_SPEC,parseLightUp,serializeLightUp,toggleLightUp,undoLightUp,type LightUpHint,type LightUpState} from '../../lib/games/light-up';

const SAVE='oiyo:light-up:v1';
const COPY={
 ko:{title:'라이트 업',sub:'빛의 논리 극장',desc:'모든 방을 밝히되 전구끼리 마주 보지 않게 배치하세요.',newGame:'새 무대',undo:'되돌리기',hint:'빛 힌트',sound:'소리',pause:'일시정지',resume:'계속하기',moves:'수',bulbs:'전구',dark:'어두운 칸',win:'모든 조명이 켜졌습니다',next:'다음 무대',restored:'저장된 무대를 불러왔어요'},
 en:{title:'Light Up',sub:'The theatre of illumination',desc:'Light every room without letting two bulbs see each other.',newGame:'New stage',undo:'Undo',hint:'Light hint',sound:'Sound',pause:'Pause',resume:'Resume',moves:'Moves',bulbs:'Bulbs',dark:'Dark cells',win:'Every light is on',next:'Next stage',restored:'Your saved stage is ready'},
 ja:{title:'美術館',sub:'光の論理劇場',desc:'電球同士を向かい合わせず、すべての部屋を照らします。',newGame:'新しい舞台',undo:'戻す',hint:'光のヒント',sound:'サウンド',pause:'一時停止',resume:'続ける',moves:'手数',bulbs:'電球',dark:'暗いマス',win:'すべての光が灯りました',next:'次の舞台',restored:'保存した舞台を復元しました'},
 zh:{title:'点灯',sub:'光之逻辑剧场',desc:'点亮所有房间，同时避免灯泡互相照射。',newGame:'新舞台',undo:'撤销',hint:'光提示',sound:'声音',pause:'暂停',resume:'继续',moves:'步数',bulbs:'灯泡',dark:'暗格',win:'所有灯光都亮了',next:'下一舞台',restored:'已恢复保存的舞台'},
 fr:{title:'Light Up',sub:"Le théâtre de lumière",desc:'Éclairez chaque pièce sans que deux ampoules se voient.',newGame:'Nouvelle scène',undo:'Annuler',hint:'Indice',sound:'Son',pause:'Pause',resume:'Reprendre',moves:'Coups',bulbs:'Ampoules',dark:'Cases sombres',win:'Toutes les lumières brillent',next:'Scène suivante',restored:'Votre scène a été restaurée'},
 es:{title:'Light Up',sub:'El teatro de la luz',desc:'Ilumina cada sala sin que dos bombillas se vean.',newGame:'Nuevo escenario',undo:'Deshacer',hint:'Pista de luz',sound:'Sonido',pause:'Pausa',resume:'Continuar',moves:'Movimientos',bulbs:'Bombillas',dark:'Casillas oscuras',win:'Todas las luces están encendidas',next:'Siguiente escenario',restored:'Tu escenario fue restaurado'}
};
const HINT:Record<keyof typeof COPY,Record<LightUpHint['reason'],string>>={ko:{clue:'벽 숫자 주변의 전구 수를 확인하세요.',conflict:'서로 마주 보는 전구를 확인하세요.',dark:'아직 빛이 닿지 않는 칸을 확인하세요.'},en:{clue:'Check the bulbs around this numbered wall.',conflict:'Check the bulbs that can see each other.',dark:'Check this cell that no light reaches yet.'},ja:{clue:'数字壁の周りの電球数を確認。',conflict:'向かい合う電球を確認。',dark:'まだ光が届かないマスを確認。'},zh:{clue:'检查数字墙周围的灯泡数。',conflict:'检查互相照射的灯泡。',dark:'检查尚未被照亮的格子。'},fr:{clue:'Vérifiez les ampoules autour du mur numéroté.',conflict:'Vérifiez les ampoules qui se voient.',dark:'Vérifiez cette case encore sombre.'},es:{clue:'Revisa las bombillas junto al muro numerado.',conflict:'Revisa las bombillas que se ven entre sí.',dark:'Revisa esta casilla aún oscura.'}};
export default function LightUp({locale='ko'}:{locale?:string}){
 const t=COPY[locale as keyof typeof COPY]??COPY.en;const [state,setState]=useState<LightUpState>(()=>createLightUp());const [paused,setPaused]=useState(false);const [sound,setSound]=useState(true);const [restored,setRestored]=useState(false);const [active,setActive]=useState(0);const [hint,setHint]=useState<LightUpHint|null>(null);const refs=useRef<Array<HTMLButtonElement|null>>([]);
 useEffect(()=>{const saved=parseLightUp(localStorage.getItem(SAVE));if(saved){setState(saved);setRestored(true);setPaused(true);}},[]);useEffect(()=>localStorage.setItem(SAVE,serializeLightUp(state)),[state]);
 const tone=useCallback((win=false)=>{if(!sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=win?880:520;g.gain.setValueAtTime(.03,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.16);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.16);},[sound]);
 const act=(fn:(s:LightUpState)=>LightUpState)=>{if(paused)return;setState(s=>{const n=fn(s);if(n!==s)tone(n.won);return n;});};const fresh=()=>{setState(createLightUp(state.seed+1));setPaused(false);setRestored(false);};const ev=evaluateAkari(LIGHT_UP_SPEC,state.bulbs);const bulbs=state.bulbs.flat().filter(Boolean).length, dark=ev.lit.flat().filter((lit,i)=>LIGHT_UP_SPEC[Math.floor(i/7)][i%7]===null&&!lit).length;
 const focus=(e:React.KeyboardEvent,index:number)=>{const r=Math.floor(index/7),c=index%7;let n=index;if(e.key==='ArrowUp')n=Math.max(0,r-1)*7+c;else if(e.key==='ArrowDown')n=Math.min(6,r+1)*7+c;else if(e.key==='ArrowLeft')n=r*7+Math.max(0,c-1);else if(e.key==='ArrowRight')n=r*7+Math.min(6,c+1);else return;e.preventDefault();while(n>=0&&n<49&&LIGHT_UP_SPEC[Math.floor(n/7)][n%7]!==null)n+=e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1;setActive(n);refs.current[n]?.focus();};
 return <GameContainer title={t.title} subtitle={t.sub} resetLabel={t.newGame} onReset={fresh}><div className="mx-auto max-w-lg space-y-5"><p className="text-center text-sm text-muted-foreground">{t.desc}</p><div className="grid grid-cols-3 gap-2"><Stat label={t.moves} value={state.moves}/><Stat label={t.bulbs} value={bulbs}/><Stat label={t.dark} value={dark}/></div>{restored&&<p className="rounded-xl bg-amber-400/15 p-3 text-center text-xs font-bold text-amber-700" role="status">{t.restored}</p>}
 <div className="relative mx-auto w-full max-w-[25rem] rounded-3xl border bg-slate-950 p-2 shadow-2xl"><div className="grid grid-cols-7 gap-1" role="grid" aria-label={t.title}>{LIGHT_UP_SPEC.flatMap((row,r)=>row.map((wall,c)=>{const i=r*7+c;if(wall!==null)return <div key={i} role="gridcell" aria-label={`wall ${wall}`} className={`aspect-square rounded-lg border border-white/10 bg-slate-800 flex items-center justify-center font-black text-white ${ev.clueErrors[r][c]?'ring-2 ring-rose-500':''}`}>{wall}</div>;const bulb=state.bulbs[r][c],lit=ev.lit[r][c],error=ev.bulbErrors[r][c];return <button key={i} ref={n=>{refs.current[i]=n;}} role="gridcell" aria-pressed={bulb} aria-label={`${r+1}, ${c+1}: ${bulb?t.bulbs:lit?'lit':t.dark}`} tabIndex={active===i?0:-1} disabled={paused||state.won} onFocus={()=>setActive(i)} onKeyDown={e=>focus(e,i)} onClick={()=>act(s=>toggleLightUp(s,i))} className={`aspect-square min-h-10 rounded-lg border transition focus-visible:ring-2 focus-visible:ring-cyan-300 ${error?'bg-rose-500':bulb?'bg-amber-300 text-xl shadow-[0_0_22px_#fcd34d]':lit?'bg-amber-100':'bg-slate-900'}`}>{bulb?'💡':''}</button>}))}</div>{paused&&<button onClick={()=>setPaused(false)} className="absolute inset-2 rounded-2xl bg-slate-950/95 text-lg font-black text-white backdrop-blur">{t.resume}</button>}</div>
 {hint&&<p className="rounded-xl border border-cyan-300/50 bg-cyan-50 p-3 text-center text-xs font-bold text-cyan-900" role="status">{HINT[locale as keyof typeof COPY]?.[hint.reason]??HINT.en[hint.reason]}{hint.cells.length?` · ${hint.cells.map(i=>`${Math.floor(i/7)+1},${i%7+1}`).join(' / ')}`:''}</p>}
 <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Control text={t.undo} onClick={()=>act(undoLightUp)} disabled={!state.history.length||state.won}/><Control text={t.hint} onClick={()=>{setHint(explainLightUpHint(state));act(hintLightUp);}} disabled={state.won}/><Control text={`${t.sound} ${sound?'ON':'OFF'}`} onClick={()=>setSound(x=>!x)}/><Control text={paused?t.resume:t.pause} onClick={()=>setPaused(x=>!x)}/></div>
 {state.won&&<div className="rounded-3xl border border-amber-300 bg-amber-100 p-6 text-center text-slate-900" role="status" aria-live="polite"><div className="text-4xl">✨</div><h3 className="mt-2 text-xl font-black">{t.win}</h3><p className="mt-1 text-sm">{state.moves} {t.moves} · {state.hints} {t.hint}</p><button onClick={fresh} className="mt-4 min-h-11 rounded-full bg-slate-900 px-8 font-bold text-white">{t.next}</button></div>}</div></GameContainer>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border bg-card p-2 text-center"><div className="text-xl font-black">{value}</div><div className="text-[10px] uppercase text-muted-foreground">{label}</div></div>};
function Control({text,onClick,disabled=false}:{text:string;onClick:()=>void;disabled?:boolean}){return <button type="button" onClick={onClick} disabled={disabled} className="min-h-11 rounded-xl border bg-card px-2 text-xs font-bold disabled:opacity-40">{text}</button>}

declare global{interface Window{webkitAudioContext?:typeof AudioContext}}
