import type { Locale } from "../../lib/i18n";
import type { BuildingId, CommandId, EventId, Terrain, TraitId, VillageTraitId, WeatherId } from "../../lib/games/village";

type Named = { name: string; hint: string };
export interface VillageCopy {
  title: string;
  sub: string;
  intro: string;
  date: string;
  seasons: [string, string, string, string];
  progress: string;
  res: { food: string; wood: string; stone: string; gold: string; pop: string; fatigue: string; safety: string; ap: string };
  villageTrait: Record<VillageTraitId, Named>;
  weather: Record<WeatherId, Named>;
  terrain: Record<Terrain, string>;
  fatigueHint: string;
  commandsTitle: string;
  cmd: Record<CommandId, Named>;
  buildTitle: string;
  placeHint: string;
  cancel: string;
  building: Record<BuildingId, Named>;
  nearForest: string;
  nearRock: string;
  project: string;
  eventTitle: string;
  needEvent: string;
  events: Record<EventId, { title: string; text: string; choices: string[] }>;
  outcome: { odds: string; safe: string; otherwise: string; harvest: string };
  endMonth: string;
  reportTitle: string;
  reportEmpty: string;
  /** Keys match the engine's report lines. */
  report: Record<string, string>;
  tile: { title: string; empty: string; worker: string; noWorker: string; none: string; send: string };
  peopleTitle: string;
  idle: string;
  auto: string;
  trait: Record<TraitId, Named>;
  names: string[];
  overTitle: string;
  score: string;
  best: string;
  grades: [string, string, string];
  again: string;
  againConfirm: string;
  save: { title: string; note: string; copy: string; copied: string; paste: string; load: string; bad: string; loaded: string };
}

export const VILLAGE_COPY: Record<Locale, VillageCopy> = {
  ko: {
    title: "작은 마을 열두 달",
    sub: "월 단위 마을 경영",
    intro: "지도, 마을 성격, 주민, 날씨, 사건이 판마다 달라요. 한 달에 행동 세 번으로 3년(36개월)을 키워 보세요.",
    date: "{y}년째 {m}월",
    seasons: ["봄", "여름", "가을", "겨울"],
    progress: "36개월 중 {n}번째 달",
    res: { food: "식량", wood: "목재", stone: "석재", gold: "금화", pop: "주민", fatigue: "피로", safety: "안전", ap: "남은 행동" },
    villageTrait: {
      fertile: { name: "기름진 들", hint: "밭 수확 +15%" },
      deepWoods: { name: "깊은 숲", hint: "목재 +25%" },
      stony: { name: "돌 많은 땅", hint: "석재 +25%" },
      crossroads: { name: "길목 마을", hint: "소식이 자주 오고 철마다 금화 +2" },
      wolfValley: { name: "늑대 골짜기", hint: "안전 -10, 사냥이 잘돼요" },
      harsh: { name: "추운 고장", hint: "겨울 장작 +1, 끝날 때 점수 +30" },
      lucky: { name: "운 좋은 마을", hint: "확률 선택의 성공률 +10%p" },
    },
    weather: {
      clear: { name: "맑음", hint: "평소대로예요" },
      rain: { name: "비", hint: "밭 수확 +25%" },
      wind: { name: "바람", hint: "목재 +20%" },
      heat: { name: "무더위", hint: "밭 수확 -20%, 피로 +3" },
      storm: { name: "폭풍", hint: "벌목장 -50%, 밭 -10%" },
      fog: { name: "안개", hint: "사냥 -2, 안전 -10" },
      snow: { name: "눈", hint: "사냥 -2, 장작 +1" },
      frost: { name: "된서리", hint: "장작 +2" },
      mild: { name: "포근한 겨울", hint: "장작이 들지 않고 사냥 +2" },
    },
    terrain: { plain: "빈 땅", fertile: "기름진 땅", forest: "숲", rock: "바위", water: "물" },
    fatigueHint: "피로가 70을 넘으면 모든 일터의 생산이 30% 줄어요. 잔치를 열거나 행동을 남긴 채 달을 마치면 피로가 내려가요.",
    commandsTitle: "촌장 명령",
    cmd: {
      tend: { name: "밭일", hint: "이번 달 수확 +50%" },
      lumber: { name: "벌목", hint: "목재 +6~10" },
      quarry: { name: "채석", hint: "석재 +4~6" },
      hunt: { name: "사냥", hint: "식량 +3~9" },
      build: { name: "건설", hint: "새로 짓거나 공사 +30" },
      patrol: { name: "순찰", hint: "이번 달 안전 +10" },
      feast: { name: "잔치", hint: "주민 수만큼 식량, 피로 -25" },
      explore: { name: "탐험", hint: "무엇이 나올지 몰라요. 피로 +6" },
    },
    buildTitle: "무엇을 지을까요?",
    placeHint: "지도에서 {name} 지을 칸을 눌러 주세요.",
    cancel: "취소",
    building: {
      field: { name: "밭", hint: "식량. 기름진 땅 +50%, 물·우물 옆 +25%" },
      house: { name: "집", hint: "주민 자리 +2" },
      storehouse: { name: "창고", hint: "보관 한도 +60" },
      lumberCamp: { name: "벌목장", hint: "달마다 목재. 숲이 많이 붙을수록 늘어요" },
      quarry: { name: "채석장", hint: "달마다 석재. 바위가 많이 붙을수록 늘어요" },
      hut: { name: "사냥막", hint: "겨울에도 식량" },
      kitchen: { name: "식당", hint: "먹는 식량 -20%, 달마다 피로 -3" },
      well: { name: "우물", hint: "옆 밭 수확 +25%" },
      watchtower: { name: "망루", hint: "안전 +15, 주민이 지키면 +25" },
      market: { name: "시장", hint: "달마다 금화 3, 옆 집마다 +1" },
      smithy: { name: "대장간", hint: "모든 일터 생산 +20%" },
      hall: { name: "마을회관", hint: "한 달 행동 +1, 끝날 때 점수 +40" },
    },
    nearForest: "숲 옆에만 지을 수 있어요",
    nearRock: "바위 옆에만 지을 수 있어요",
    project: "짓는 중: {name} {p}/{n}",
    eventTitle: "이번 달 소식",
    needEvent: "먼저 이번 달 소식을 정해 주세요.",
    events: {
      drought: { title: "가뭄", text: "비가 오지 않아 밭이 말라 가요.", choices: ["물을 길어 온다", "그냥 둔다"] },
      bumper: { title: "풍년", text: "날씨가 도와서 작물이 잘 자라요.", choices: ["좋아요"] },
      trader: { title: "떠돌이 상인", text: "상인이 마을 어귀에 짐을 풀었어요.", choices: ["목재를 판다", "식량을 산다", "그냥 보낸다"] },
      wolves: { title: "늑대", text: "밤마다 늑대 울음이 가까워져요.", choices: ["맞선다", "숨는다"] },
      coldSnap: { title: "한파", text: "유난히 추운 밤이 이어져요.", choices: ["장작을 더 땐다", "버틴다"] },
      festival: { title: "마을 잔칫날", text: "주민들이 하루 쉬어 가자고 해요.", choices: ["잔치를 연다", "다음으로 미룬다"] },
      sickness: { title: "돌림병", text: "기침하는 주민이 늘었어요.", choices: ["쉬게 한다", "약을 산다"] },
      traveler: { title: "나그네", text: "지나가던 나그네가 머물 곳을 찾아요.", choices: ["주민으로 맞는다", "길을 알려 준다"] },
      gambler: { title: "노름꾼", text: "떠돌이 노름꾼이 한 판 하자고 해요.", choices: ["한 판 건다", "거절한다"] },
      ruins: { title: "옛 집터", text: "숲 가장자리에서 오래된 집터를 찾았어요.", choices: ["파 본다", "그대로 둔다"] },
      bees: { title: "벌집", text: "큰 벌집이 나무에 달렸어요.", choices: ["꿀을 딴다", "건드리지 않는다"] },
      storm: { title: "폭풍 예보", text: "하늘이 심상치 않아요.", choices: ["지붕을 덧댄다", "그냥 넘긴다"] },
      bandits: { title: "도적", text: "도적 무리가 통행세를 내라고 해요.", choices: ["돈을 준다", "맞선다"] },
      fishRun: { title: "물고기 떼", text: "개울에 물고기 떼가 올라왔어요.", choices: ["모두 나가 잡는다", "지나친다"] },
      lostChild: { title: "길 잃은 아이", text: "이웃 마을 아이가 숲에서 길을 잃었대요.", choices: ["찾으러 간다", "모른 척한다"] },
      caravan: { title: "큰 상단", text: "큰 상단이 마을에 들렀어요.", choices: ["식량을 판다", "석재를 산다", "구경만 한다"] },
      fire: { title: "불이야", text: "헛간에서 불이 났어요.", choices: ["모두 나서서 끈다", "탈 만큼 타게 둔다"] },
      heavySnow: { title: "폭설", text: "밤새 눈이 허리까지 쌓였어요.", choices: ["눈을 치운다", "녹기를 기다린다"] },
      shootingStar: { title: "별똥별", text: "밤하늘에 별똥별이 쏟아졌어요.", choices: ["다 같이 구경한다"] },
      rats: { title: "쥐 떼", text: "곳간에 쥐가 들었어요.", choices: ["덫을 놓는다", "그냥 둔다"] },
      healer: { title: "떠돌이 의원", text: "솜씨 좋은 의원이 하루 묵어 가요.", choices: ["모두 진찰받는다", "보낸다"] },
      mushrooms: { title: "버섯", text: "숲에 처음 보는 버섯이 잔뜩 났어요.", choices: ["따서 먹는다", "두고 온다"] },
      taxman: { title: "세금", text: "관아에서 세금을 걷으러 왔어요.", choices: ["낸다", "사정해 본다"] },
      family: { title: "이주 가족", text: "살 곳을 찾는 가족이 찾아왔어요.", choices: ["맞아들인다", "길을 알려 준다"] },
    },
    outcome: { odds: "성공 확률 {n}%", safe: "안전 {n} 이상이면 성공", otherwise: "실패하면", harvest: "이번 달 수확 {n}%" },
    endMonth: "이번 달 마치기",
    reportTitle: "지난달 결과",
    reportEmpty: "아직 지난달이 없어요.",
    report: {
      weather: "날씨: {name}", tired: "모두 지쳐서 생산이 줄었어요", made: "일터에서 {name} +{n}", idle: "일 없는 주민 {n}명",
      built: "{name} 완성", eaten: "먹은 식량 {n}", hungry: "식량이 모자라 굶었어요", left: "주민 {name} 님이 마을을 떠났어요",
      firewood: "장작으로 목재 {n}", cold: "장작이 없어 추위에 떨었어요", newcomer: "새 주민이 왔어요", tax: "철마다 모은 금화 +{n}",
      tended: "밭을 돌봤어요", patrolled: "마을을 돌았어요", nothing: "아무것도 찾지 못했어요", treasure: "묻힌 보물을 찾았어요!",
      progress: "{name} 공사 {n}", good: "잘됐어요", bad: "잘 안됐어요", harvestMod: "이번 달 수확 {n}%", delta: "{name} {n}",
    },
    tile: { title: "고른 칸", empty: "아무것도 없어요", worker: "일하는 주민", noWorker: "일하는 주민이 없어서 쉬고 있어요", none: "아무도 안 보냄", send: "보낼 주민" },
    peopleTitle: "주민",
    idle: "일 없음",
    auto: "빈 일터에 알아서 보내기",
    trait: {
      diligent: { name: "부지런함", hint: "일 +25%" },
      strong: { name: "힘셈", hint: "벌목장·채석장 +50%" },
      greenThumb: { name: "농사꾼", hint: "밭 +50%" },
      glutton: { name: "대식가", hint: "식량을 3 먹어요" },
      frugal: { name: "소식가", hint: "식량을 1만 먹어요" },
      lazy: { name: "게으름", hint: "일 -25%" },
      brave: { name: "용감함", hint: "안전 +5" },
      merchant: { name: "장사꾼", hint: "시장 +50%, 철마다 금화 +1" },
    },
    names: ["돌쇠", "순이", "막동", "분이", "길동", "달래", "천석", "꽃분", "바우", "옥이", "만수", "점례", "억쇠", "금이", "삼돌", "복실", "칠성", "이쁜", "장쇠", "솔이", "두리", "보배", "강쇠", "은실"],
    overTitle: "3년이 지났어요",
    score: "점수",
    best: "최고 점수",
    grades: ["작은 마을", "번듯한 마을", "이름난 마을"],
    again: "새 마을 시작",
    againConfirm: "지금 마을을 지우고 새로 시작할까요?",
    save: {
      title: "세이브 코드",
      note: "이 브라우저에 자동으로 저장돼요. 코드를 복사해 다른 기기에 붙여 넣으면 이어서 할 수 있어요. 서버로는 보내지 않아요.",
      copy: "코드 복사", copied: "복사했어요", paste: "코드를 여기에 붙여 넣으세요", load: "불러오기",
      bad: "읽을 수 없는 코드예요. 지금 마을은 그대로 두었어요.", loaded: "마을을 불러왔어요",
    },
  },
  en: {
    title: "Twelve Months, One Village",
    sub: "Month-by-month village sim",
    intro: "The map, the village's character, the villagers, the weather and the news differ every run. Three actions a month, three years (36 months).",
    date: "Year {y}, month {m}",
    seasons: ["Spring", "Summer", "Autumn", "Winter"],
    progress: "Month {n} of 36",
    res: { food: "Food", wood: "Wood", stone: "Stone", gold: "Gold", pop: "Villagers", fatigue: "Fatigue", safety: "Safety", ap: "Actions left" },
    villageTrait: {
      fertile: { name: "Rich soil", hint: "Fields +15%" },
      deepWoods: { name: "Deep woods", hint: "Wood +25%" },
      stony: { name: "Stony ground", hint: "Stone +25%" },
      crossroads: { name: "Crossroads", hint: "News comes often, gold +2 a season" },
      wolfValley: { name: "Wolf valley", hint: "Safety -10, hunting is good" },
      harsh: { name: "Cold country", hint: "Firewood +1 in winter, +30 score at the end" },
      lucky: { name: "Lucky village", hint: "Risky choices succeed 10 points more often" },
    },
    weather: {
      clear: { name: "Clear", hint: "Nothing unusual" },
      rain: { name: "Rain", hint: "Fields +25%" },
      wind: { name: "Windy", hint: "Wood +20%" },
      heat: { name: "Heatwave", hint: "Fields -20%, fatigue +3" },
      storm: { name: "Storm", hint: "Lumber camps -50%, fields -10%" },
      fog: { name: "Fog", hint: "Hunting -2, safety -10" },
      snow: { name: "Snow", hint: "Hunting -2, firewood +1" },
      frost: { name: "Hard frost", hint: "Firewood +2" },
      mild: { name: "Mild winter", hint: "No firewood needed, hunting +2" },
    },
    terrain: { plain: "Open ground", fertile: "Rich soil", forest: "Forest", rock: "Rock", water: "Water" },
    fatigueHint: "Above 70 fatigue every workplace makes 30% less. A feast, or ending the month with actions unspent, brings it down.",
    commandsTitle: "Chief's orders",
    cmd: {
      tend: { name: "Tend fields", hint: "Harvest +50% this month" },
      lumber: { name: "Cut wood", hint: "Wood +6 to 10" },
      quarry: { name: "Quarry", hint: "Stone +4 to 6" },
      hunt: { name: "Hunt", hint: "Food +3 to 9" },
      build: { name: "Build", hint: "Start a building or add 30 work" },
      patrol: { name: "Patrol", hint: "Safety +10 this month" },
      feast: { name: "Feast", hint: "Food per villager, fatigue -25" },
      explore: { name: "Explore", hint: "You never know. Fatigue +6" },
    },
    buildTitle: "What should we build?",
    placeHint: "Tap a tile on the map for the {name}.",
    cancel: "Cancel",
    building: {
      field: { name: "Field", hint: "Food. Rich soil +50%, beside water or a well +25%" },
      house: { name: "House", hint: "Room for 2 more villagers" },
      storehouse: { name: "Storehouse", hint: "Storage limit +60" },
      lumberCamp: { name: "Lumber camp", hint: "Wood every month, more with more forest around" },
      quarry: { name: "Quarry pit", hint: "Stone every month, more with more rock around" },
      hut: { name: "Hunting lodge", hint: "Food, even in winter" },
      kitchen: { name: "Kitchen", hint: "Food eaten -20%, fatigue -3 a month" },
      well: { name: "Well", hint: "Fields beside it +25%" },
      watchtower: { name: "Watchtower", hint: "Safety +15, or +25 with a guard" },
      market: { name: "Market", hint: "Gold 3 a month, +1 per house beside it" },
      smithy: { name: "Smithy", hint: "Every workplace +20%" },
      hall: { name: "Village hall", hint: "One more action a month, +40 score at the end" },
    },
    nearForest: "Must stand beside forest",
    nearRock: "Must stand beside rock",
    project: "Building: {name} {p}/{n}",
    eventTitle: "This month's news",
    needEvent: "Decide this month's news first.",
    events: {
      drought: { title: "Drought", text: "No rain, and the fields are drying out.", choices: ["Carry water", "Let it be"] },
      bumper: { title: "Good weather", text: "The weather is kind and the crops are thriving.", choices: ["Lovely"] },
      trader: { title: "Travelling trader", text: "A trader has set up at the edge of the village.", choices: ["Sell wood", "Buy food", "Send them on"] },
      wolves: { title: "Wolves", text: "The howling gets closer every night.", choices: ["Stand guard", "Hide"] },
      coldSnap: { title: "Cold snap", text: "The nights have turned bitterly cold.", choices: ["Burn more wood", "Tough it out"] },
      festival: { title: "Feast day", text: "The villagers would like a day off.", choices: ["Hold the feast", "Put it off"] },
      sickness: { title: "Sickness", text: "More villagers are coughing.", choices: ["Let them rest", "Buy medicine"] },
      traveler: { title: "A traveller", text: "A passing traveller is looking for a place to stay.", choices: ["Welcome them", "Point the way"] },
      gambler: { title: "A gambler", text: "A wandering gambler offers a game.", choices: ["Place a bet", "Decline"] },
      ruins: { title: "Old foundations", text: "Someone found old foundations at the forest's edge.", choices: ["Dig", "Leave them"] },
      bees: { title: "A beehive", text: "A big hive is hanging in a tree.", choices: ["Take the honey", "Leave it alone"] },
      storm: { title: "Storm warning", text: "The sky looks wrong.", choices: ["Patch the roofs", "Ride it out"] },
      bandits: { title: "Bandits", text: "A band of robbers demands a toll.", choices: ["Pay them", "Stand up to them"] },
      fishRun: { title: "Fish run", text: "The stream is thick with fish.", choices: ["Everyone goes fishing", "Let it pass"] },
      lostChild: { title: "A lost child", text: "A child from the next village is lost in the woods.", choices: ["Go and search", "Look away"] },
      caravan: { title: "A caravan", text: "A large caravan has stopped at the village.", choices: ["Sell food", "Buy stone", "Just look"] },
      fire: { title: "Fire!", text: "A shed has caught fire.", choices: ["Everyone fights it", "Let it burn out"] },
      heavySnow: { title: "Heavy snow", text: "Snow piled waist-deep overnight.", choices: ["Shovel it", "Wait for the thaw"] },
      shootingStar: { title: "Shooting stars", text: "The night sky is full of falling stars.", choices: ["Watch together"] },
      rats: { title: "Rats", text: "Rats have got into the granary.", choices: ["Set traps", "Ignore them"] },
      healer: { title: "A travelling healer", text: "A skilled healer is staying one night.", choices: ["Everyone gets seen", "Send them on"] },
      mushrooms: { title: "Mushrooms", text: "The woods are full of mushrooms nobody recognises.", choices: ["Pick and eat them", "Leave them"] },
      taxman: { title: "Taxes", text: "The tax collector has come.", choices: ["Pay", "Plead"] },
      family: { title: "A family", text: "A family is looking for somewhere to live.", choices: ["Take them in", "Point the way"] },
    },
    outcome: { odds: "{n}% chance of success", safe: "Succeeds at safety {n} or more", otherwise: "If it fails", harvest: "harvest {n}% this month" },
    endMonth: "End the month",
    reportTitle: "Last month",
    reportEmpty: "No month has passed yet.",
    report: {
      weather: "Weather: {name}", tired: "Everyone was worn out, so less got done", made: "Workplaces: {name} +{n}", idle: "Villagers without work: {n}",
      built: "{name} finished", eaten: "Food eaten: {n}", hungry: "There was not enough food", left: "{name} left the village",
      firewood: "Firewood: wood {n}", cold: "No firewood, a cold month", newcomer: "A new villager arrived", tax: "Season's gold: +{n}",
      tended: "The fields were tended", patrolled: "The village was patrolled", nothing: "Nothing was found", treasure: "Buried treasure!",
      progress: "{name}: work {n}", good: "It went well", bad: "It went badly", harvestMod: "Harvest {n}% this month", delta: "{name} {n}",
    },
    tile: { title: "Selected tile", empty: "Nothing here", worker: "Worker", noWorker: "Nobody works here, so it stands idle", none: "Nobody", send: "Send" },
    peopleTitle: "Villagers",
    idle: "No work",
    auto: "Send idle villagers to empty workplaces",
    trait: {
      diligent: { name: "Diligent", hint: "Work +25%" },
      strong: { name: "Strong", hint: "Lumber camp and quarry +50%" },
      greenThumb: { name: "Green thumb", hint: "Fields +50%" },
      glutton: { name: "Big eater", hint: "Eats 3 food" },
      frugal: { name: "Light eater", hint: "Eats only 1 food" },
      lazy: { name: "Lazy", hint: "Work -25%" },
      brave: { name: "Brave", hint: "Safety +5" },
      merchant: { name: "Trader", hint: "Market +50%, gold +1 a season" },
    },
    names: ["Alder", "Bess", "Corin", "Dilly", "Edric", "Fern", "Garth", "Hazel", "Ivo", "Juniper", "Kit", "Linnet", "Marlo", "Nell", "Osric", "Poppy", "Quill", "Rowan", "Sorrel", "Tam", "Una", "Wren", "Yarrow", "Zeke"],
    overTitle: "Three years have passed",
    score: "Score",
    best: "Best score",
    grades: ["Small village", "Proper village", "Famous village"],
    again: "Start a new village",
    againConfirm: "Erase this village and start again?",
    save: {
      title: "Save code",
      note: "Your village is saved in this browser automatically. Copy the code and paste it on another device to carry on there. Nothing is sent to a server.",
      copy: "Copy code", copied: "Copied", paste: "Paste a code here", load: "Load",
      bad: "That code could not be read. Your village was left as it is.", loaded: "Village loaded",
    },
  },
  ja: {
    title: "小さな村の十二か月",
    sub: "月ごとの村づくり",
    intro: "地図、村の性格、村人、天気、知らせが毎回変わります。1か月に3回の行動で、3年(36か月)村を育ててください。",
    date: "{y}年目 {m}月",
    seasons: ["春", "夏", "秋", "冬"],
    progress: "36か月中 {n}か月目",
    res: { food: "食料", wood: "木材", stone: "石材", gold: "金貨", pop: "村人", fatigue: "疲れ", safety: "安全", ap: "残り行動" },
    villageTrait: {
      fertile: { name: "肥えた野", hint: "畑の収穫 +15%" },
      deepWoods: { name: "深い森", hint: "木材 +25%" },
      stony: { name: "石の多い土地", hint: "石材 +25%" },
      crossroads: { name: "街道の村", hint: "知らせがよく届き、季節ごとに金貨 +2" },
      wolfValley: { name: "オオカミ谷", hint: "安全 -10、狩りがはかどります" },
      harsh: { name: "寒い土地", hint: "冬の薪 +1、終了時にスコア +30" },
      lucky: { name: "運のいい村", hint: "確率の選択の成功率 +10ポイント" },
    },
    weather: {
      clear: { name: "晴れ", hint: "いつもどおりです" },
      rain: { name: "雨", hint: "畑の収穫 +25%" },
      wind: { name: "風", hint: "木材 +20%" },
      heat: { name: "猛暑", hint: "畑の収穫 -20%、疲れ +3" },
      storm: { name: "嵐", hint: "伐採場 -50%、畑 -10%" },
      fog: { name: "霧", hint: "狩り -2、安全 -10" },
      snow: { name: "雪", hint: "狩り -2、薪 +1" },
      frost: { name: "厳しい霜", hint: "薪 +2" },
      mild: { name: "暖冬", hint: "薪がいらず、狩り +2" },
    },
    terrain: { plain: "空き地", fertile: "肥えた土", forest: "森", rock: "岩", water: "水" },
    fatigueHint: "疲れが70を超えると、すべての仕事場の生産が30%減ります。宴を開くか、行動を残して月を終えると疲れが下がります。",
    commandsTitle: "村長の指示",
    cmd: {
      tend: { name: "畑仕事", hint: "今月の収穫 +50%" },
      lumber: { name: "伐採", hint: "木材 +6〜10" },
      quarry: { name: "採石", hint: "石材 +4〜6" },
      hunt: { name: "狩り", hint: "食料 +3〜9" },
      build: { name: "建設", hint: "新しく建てる、または工事 +30" },
      patrol: { name: "見回り", hint: "今月の安全 +10" },
      feast: { name: "宴", hint: "村人の数だけ食料、疲れ -25" },
      explore: { name: "探検", hint: "何が出るかわかりません。疲れ +6" },
    },
    buildTitle: "何を建てますか？",
    placeHint: "{name}を建てるマスを地図で選んでください。",
    cancel: "キャンセル",
    building: {
      field: { name: "畑", hint: "食料。肥えた土 +50%、水や井戸の隣 +25%" },
      house: { name: "家", hint: "村人の枠 +2" },
      storehouse: { name: "倉庫", hint: "保管上限 +60" },
      lumberCamp: { name: "伐採場", hint: "毎月木材。隣の森が多いほど増えます" },
      quarry: { name: "採石場", hint: "毎月石材。隣の岩が多いほど増えます" },
      hut: { name: "狩り小屋", hint: "冬でも食料" },
      kitchen: { name: "食堂", hint: "食べる食料 -20%、毎月疲れ -3" },
      well: { name: "井戸", hint: "隣の畑の収穫 +25%" },
      watchtower: { name: "見張り台", hint: "安全 +15、村人が守ると +25" },
      market: { name: "市場", hint: "毎月金貨3、隣の家ごとに +1" },
      smithy: { name: "鍛冶場", hint: "すべての仕事場の生産 +20%" },
      hall: { name: "集会所", hint: "毎月の行動 +1、終了時にスコア +40" },
    },
    nearForest: "森の隣にしか建てられません",
    nearRock: "岩の隣にしか建てられません",
    project: "建設中: {name} {p}/{n}",
    eventTitle: "今月の知らせ",
    needEvent: "先に今月の知らせを決めてください。",
    events: {
      drought: { title: "日照り", text: "雨が降らず、畑が乾いてきました。", choices: ["水をくんでくる", "そのままにする"] },
      bumper: { title: "豊作", text: "天気に恵まれて作物がよく育っています。", choices: ["よかった"] },
      trader: { title: "旅の商人", text: "商人が村の入り口で荷をほどきました。", choices: ["木材を売る", "食料を買う", "見送る"] },
      wolves: { title: "オオカミ", text: "夜ごとに遠吠えが近づいてきます。", choices: ["立ち向かう", "隠れる"] },
      coldSnap: { title: "寒波", text: "ひときわ寒い夜が続いています。", choices: ["薪を多くたく", "がまんする"] },
      festival: { title: "祭りの日", text: "村人たちが一日休みたいと言っています。", choices: ["祭りを開く", "また今度にする"] },
      sickness: { title: "はやり病", text: "せきをする村人が増えました。", choices: ["休ませる", "薬を買う"] },
      traveler: { title: "旅人", text: "通りがかりの旅人が泊まる場所を探しています。", choices: ["村人として迎える", "道を教える"] },
      gambler: { title: "ばくち打ち", text: "流れ者のばくち打ちが一勝負しようと言います。", choices: ["賭ける", "断る"] },
      ruins: { title: "古い屋敷跡", text: "森の端で古い屋敷跡が見つかりました。", choices: ["掘ってみる", "そのままにする"] },
      bees: { title: "ハチの巣", text: "大きなハチの巣が木にぶら下がっています。", choices: ["蜜を取る", "手を出さない"] },
      storm: { title: "嵐の予感", text: "空のようすがおかしいです。", choices: ["屋根を補強する", "やり過ごす"] },
      bandits: { title: "盗賊", text: "盗賊の一団が通行料を出せと言っています。", choices: ["金を払う", "立ち向かう"] },
      fishRun: { title: "魚の群れ", text: "小川に魚の群れが上ってきました。", choices: ["みんなで取りに行く", "見送る"] },
      lostChild: { title: "迷子", text: "隣村の子どもが森で迷ったそうです。", choices: ["探しに行く", "知らないふりをする"] },
      caravan: { title: "大きな隊商", text: "大きな隊商が村に立ち寄りました。", choices: ["食料を売る", "石材を買う", "見るだけにする"] },
      fire: { title: "火事だ", text: "納屋から火が出ました。", choices: ["みんなで消す", "燃えるにまかせる"] },
      heavySnow: { title: "大雪", text: "一晩で腰まで雪が積もりました。", choices: ["雪かきをする", "とけるのを待つ"] },
      shootingStar: { title: "流れ星", text: "夜空に流れ星が降りそそぎました。", choices: ["みんなで眺める"] },
      rats: { title: "ネズミ", text: "蔵にネズミが入りました。", choices: ["わなを仕掛ける", "放っておく"] },
      healer: { title: "旅の医者", text: "腕のいい医者が一晩泊まっていきます。", choices: ["みんな診てもらう", "見送る"] },
      mushrooms: { title: "キノコ", text: "森に見慣れないキノコがたくさん生えました。", choices: ["取って食べる", "置いてくる"] },
      taxman: { title: "年貢", text: "役人が年貢を取りに来ました。", choices: ["納める", "頼みこむ"] },
      family: { title: "移り住む家族", text: "住む場所を探している家族が訪ねてきました。", choices: ["迎え入れる", "道を教える"] },
    },
    outcome: { odds: "成功率 {n}%", safe: "安全 {n} 以上なら成功", otherwise: "失敗すると", harvest: "今月の収穫 {n}%" },
    endMonth: "今月を終える",
    reportTitle: "先月の結果",
    reportEmpty: "まだ先月はありません。",
    report: {
      weather: "天気: {name}", tired: "みんな疲れて生産が減りました", made: "仕事場から {name} +{n}", idle: "仕事のない村人 {n}人",
      built: "{name}が完成", eaten: "食べた食料 {n}", hungry: "食料が足りず飢えました", left: "{name}が村を去りました",
      firewood: "薪として木材 {n}", cold: "薪がなく寒さに震えました", newcomer: "新しい村人が来ました", tax: "季節ごとの金貨 +{n}",
      tended: "畑の世話をしました", patrolled: "村を見回りました", nothing: "何も見つかりませんでした", treasure: "埋もれた宝を見つけました！",
      progress: "{name} 工事 {n}", good: "うまくいきました", bad: "うまくいきませんでした", harvestMod: "今月の収穫 {n}%", delta: "{name} {n}",
    },
    tile: { title: "選んだマス", empty: "何もありません", worker: "働く村人", noWorker: "働く村人がいないので止まっています", none: "だれも送らない", send: "送る村人" },
    peopleTitle: "村人",
    idle: "仕事なし",
    auto: "空いた仕事場におまかせで送る",
    trait: {
      diligent: { name: "働き者", hint: "仕事 +25%" },
      strong: { name: "力持ち", hint: "伐採場・採石場 +50%" },
      greenThumb: { name: "畑上手", hint: "畑 +50%" },
      glutton: { name: "大食い", hint: "食料を3食べます" },
      frugal: { name: "小食", hint: "食料を1しか食べません" },
      lazy: { name: "なまけ者", hint: "仕事 -25%" },
      brave: { name: "勇敢", hint: "安全 +5" },
      merchant: { name: "商売上手", hint: "市場 +50%、季節ごとに金貨 +1" },
    },
    names: ["太郎", "お花", "次郎", "おみつ", "権太", "おつる", "三吉", "おはる", "与作", "おたま", "弥助", "おきぬ", "源太", "おふく", "茂吉", "おゆき", "平八", "おさと", "熊吉", "おなつ", "新太", "おこま", "伊助", "おりん"],
    overTitle: "3年がたちました",
    score: "スコア",
    best: "ベストスコア",
    grades: ["小さな村", "立派な村", "名の知れた村"],
    again: "新しい村を始める",
    againConfirm: "今の村を消して最初から始めますか？",
    save: {
      title: "セーブコード",
      note: "このブラウザーに自動で保存されます。コードをコピーして別の端末に貼り付けると続きができます。サーバーには送信しません。",
      copy: "コードをコピー", copied: "コピーしました", paste: "ここにコードを貼り付けてください", load: "読み込む",
      bad: "読み取れないコードです。今の村はそのままです。", loaded: "村を読み込みました",
    },
  },
  zh: {
    title: "小村庄的十二个月",
    sub: "按月经营的村庄",
    intro: "地图、村庄特点、村民、天气和消息每局都不同。每月行动三次，把村庄经营满三年(36个月)。",
    date: "第{y}年 {m}月",
    seasons: ["春", "夏", "秋", "冬"],
    progress: "36个月中的第{n}个月",
    res: { food: "粮食", wood: "木材", stone: "石材", gold: "金币", pop: "村民", fatigue: "疲劳", safety: "安全", ap: "剩余行动" },
    villageTrait: {
      fertile: { name: "肥沃的原野", hint: "田地收成 +15%" },
      deepWoods: { name: "深林", hint: "木材 +25%" },
      stony: { name: "多石之地", hint: "石材 +25%" },
      crossroads: { name: "路口村", hint: "消息更多，每季金币 +2" },
      wolfValley: { name: "狼谷", hint: "安全 -10，打猎更顺" },
      harsh: { name: "苦寒之地", hint: "冬季柴火 +1，结束时分数 +30" },
      lucky: { name: "好运村", hint: "概率选择的成功率 +10个百分点" },
    },
    weather: {
      clear: { name: "晴", hint: "一切如常" },
      rain: { name: "雨", hint: "田地收成 +25%" },
      wind: { name: "大风", hint: "木材 +20%" },
      heat: { name: "酷暑", hint: "田地收成 -20%，疲劳 +3" },
      storm: { name: "暴风雨", hint: "伐木场 -50%，田地 -10%" },
      fog: { name: "大雾", hint: "打猎 -2，安全 -10" },
      snow: { name: "雪", hint: "打猎 -2，柴火 +1" },
      frost: { name: "严霜", hint: "柴火 +2" },
      mild: { name: "暖冬", hint: "不用烧柴，打猎 +2" },
    },
    terrain: { plain: "空地", fertile: "沃土", forest: "森林", rock: "岩石", water: "水" },
    fatigueHint: "疲劳超过70时，所有工作场所的产量减少30%。办宴会，或者留着行动不用就结束本月，疲劳会下降。",
    commandsTitle: "村长指令",
    cmd: {
      tend: { name: "照料田地", hint: "本月收成 +50%" },
      lumber: { name: "伐木", hint: "木材 +6~10" },
      quarry: { name: "采石", hint: "石材 +4~6" },
      hunt: { name: "打猎", hint: "粮食 +3~9" },
      build: { name: "建造", hint: "新建，或工程 +30" },
      patrol: { name: "巡逻", hint: "本月安全 +10" },
      feast: { name: "宴会", hint: "按人数消耗粮食，疲劳 -25" },
      explore: { name: "探索", hint: "不知道会遇到什么。疲劳 +6" },
    },
    buildTitle: "要建什么？",
    placeHint: "请在地图上点选建造{name}的格子。",
    cancel: "取消",
    building: {
      field: { name: "田地", hint: "产粮。沃土 +50%，挨着水或水井 +25%" },
      house: { name: "房屋", hint: "村民名额 +2" },
      storehouse: { name: "仓库", hint: "储存上限 +60" },
      lumberCamp: { name: "伐木场", hint: "每月产木材，周围森林越多越高" },
      quarry: { name: "采石场", hint: "每月产石材，周围岩石越多越高" },
      hut: { name: "猎人小屋", hint: "冬天也能产粮" },
      kitchen: { name: "食堂", hint: "粮食消耗 -20%，每月疲劳 -3" },
      well: { name: "水井", hint: "旁边田地收成 +25%" },
      watchtower: { name: "瞭望塔", hint: "安全 +15，有人驻守则 +25" },
      market: { name: "集市", hint: "每月金币3，旁边每座房屋 +1" },
      smithy: { name: "铁匠铺", hint: "所有工作场所产量 +20%" },
      hall: { name: "村公所", hint: "每月行动 +1，结束时分数 +40" },
    },
    nearForest: "只能建在森林旁边",
    nearRock: "只能建在岩石旁边",
    project: "建造中：{name} {p}/{n}",
    eventTitle: "本月消息",
    needEvent: "请先决定本月的消息。",
    events: {
      drought: { title: "干旱", text: "一直不下雨，田地快干了。", choices: ["去挑水", "不管它"] },
      bumper: { title: "丰收", text: "天气帮忙，庄稼长得很好。", choices: ["太好了"] },
      trader: { title: "行商", text: "一位商人在村口摆开了货物。", choices: ["卖木材", "买粮食", "让他走"] },
      wolves: { title: "狼群", text: "每晚的狼嚎越来越近。", choices: ["迎战", "躲起来"] },
      coldSnap: { title: "寒潮", text: "夜里格外寒冷。", choices: ["多烧柴", "硬撑"] },
      festival: { title: "节日", text: "村民们想休息一天。", choices: ["办宴会", "下次再说"] },
      sickness: { title: "流行病", text: "咳嗽的村民变多了。", choices: ["让他们休息", "买药"] },
      traveler: { title: "旅人", text: "一位路过的旅人在找落脚的地方。", choices: ["收留为村民", "给他指路"] },
      gambler: { title: "赌徒", text: "一个流浪赌徒想赌一把。", choices: ["赌一把", "拒绝"] },
      ruins: { title: "旧宅基", text: "有人在林边发现了一处旧宅基。", choices: ["挖挖看", "不去动它"] },
      bees: { title: "蜂巢", text: "树上挂着一个大蜂巢。", choices: ["取蜂蜜", "不去招惹"] },
      storm: { title: "风暴将至", text: "天色不对劲。", choices: ["加固屋顶", "听天由命"] },
      bandits: { title: "强盗", text: "一伙强盗要收过路钱。", choices: ["给钱", "对抗"] },
      fishRun: { title: "鱼群", text: "小溪里游来了一大群鱼。", choices: ["全村去捕", "错过算了"] },
      lostChild: { title: "迷路的孩子", text: "听说邻村的孩子在林子里迷路了。", choices: ["去找", "装作不知道"] },
      caravan: { title: "大商队", text: "一支大商队在村里歇脚。", choices: ["卖粮食", "买石材", "只看看"] },
      fire: { title: "着火了", text: "柴房起火了。", choices: ["全村救火", "让它烧完"] },
      heavySnow: { title: "暴雪", text: "一夜之间雪积到了腰。", choices: ["铲雪", "等它化"] },
      shootingStar: { title: "流星", text: "夜空中下起了流星雨。", choices: ["一起看"] },
      rats: { title: "老鼠", text: "粮仓进了老鼠。", choices: ["放捕鼠夹", "不管"] },
      healer: { title: "游方郎中", text: "一位医术好的郎中借宿一晚。", choices: ["大家都看看", "送他走"] },
      mushrooms: { title: "蘑菇", text: "林子里长满了没见过的蘑菇。", choices: ["采来吃", "不去碰"] },
      taxman: { title: "收税", text: "官府派人来收税了。", choices: ["交税", "求情"] },
      family: { title: "迁来的一家人", text: "有一家人在找地方安家。", choices: ["收留他们", "给他们指路"] },
    },
    outcome: { odds: "成功率 {n}%", safe: "安全达到 {n} 则成功", otherwise: "失败时", harvest: "本月收成 {n}%" },
    endMonth: "结束本月",
    reportTitle: "上个月的结果",
    reportEmpty: "还没有过去的月份。",
    report: {
      weather: "天气：{name}", tired: "大家太累，产量减少了", made: "工作场所产出{name} +{n}", idle: "没有工作的村民 {n} 人",
      built: "{name}建成", eaten: "消耗粮食 {n}", hungry: "粮食不够，挨饿了", left: "{name}离开了村庄",
      firewood: "烧柴消耗木材 {n}", cold: "没有柴火，冻了一个月", newcomer: "来了一位新村民", tax: "当季金币 +{n}",
      tended: "照料了田地", patrolled: "巡视了村庄", nothing: "什么也没找到", treasure: "挖到了埋藏的宝物！",
      progress: "{name}工程 {n}", good: "很顺利", bad: "不太顺利", harvestMod: "本月收成 {n}%", delta: "{name} {n}",
    },
    tile: { title: "选中的格子", empty: "这里什么都没有", worker: "工作的村民", noWorker: "没有人在这里工作，所以停着", none: "不派人", send: "派谁去" },
    peopleTitle: "村民",
    idle: "没有工作",
    auto: "自动派到空着的工作场所",
    trait: {
      diligent: { name: "勤快", hint: "工作 +25%" },
      strong: { name: "力气大", hint: "伐木场、采石场 +50%" },
      greenThumb: { name: "种田好手", hint: "田地 +50%" },
      glutton: { name: "大胃王", hint: "吃3份粮食" },
      frugal: { name: "饭量小", hint: "只吃1份粮食" },
      lazy: { name: "懒散", hint: "工作 -25%" },
      brave: { name: "勇敢", hint: "安全 +5" },
      merchant: { name: "会做生意", hint: "集市 +50%，每季金币 +1" },
    },
    names: ["阿福", "小翠", "大牛", "春花", "石头", "秀兰", "铁柱", "桂香", "二虎", "彩云", "根生", "玉梅", "长顺", "巧儿", "满仓", "杏儿", "栓子", "月娥", "水生", "荷花", "三宝", "银凤", "狗剩", "腊梅"],
    overTitle: "三年过去了",
    score: "分数",
    best: "最高分",
    grades: ["小村庄", "像样的村庄", "出名的村庄"],
    again: "开始新村庄",
    againConfirm: "要清除当前村庄并重新开始吗？",
    save: {
      title: "存档码",
      note: "村庄会自动保存在此浏览器中。复制存档码并粘贴到另一台设备上，就能接着玩。不会发送到服务器。",
      copy: "复制存档码", copied: "已复制", paste: "在这里粘贴存档码", load: "读取",
      bad: "无法读取这个存档码。当前村庄保持不变。", loaded: "已读取村庄",
    },
  },
  fr: {
    title: "Douze mois, un village",
    sub: "Gestion de village mois par mois",
    intro: "La carte, le caractère du village, les villageois, la météo et les nouvelles changent à chaque partie. Trois actions par mois, trois ans (36 mois).",
    date: "Année {y}, mois {m}",
    seasons: ["Printemps", "Été", "Automne", "Hiver"],
    progress: "Mois {n} sur 36",
    res: { food: "Nourriture", wood: "Bois", stone: "Pierre", gold: "Or", pop: "Villageois", fatigue: "Fatigue", safety: "Sécurité", ap: "Actions restantes" },
    villageTrait: {
      fertile: { name: "Terres grasses", hint: "Champs +15 %" },
      deepWoods: { name: "Forêt profonde", hint: "Bois +25 %" },
      stony: { name: "Sol pierreux", hint: "Pierre +25 %" },
      crossroads: { name: "Carrefour", hint: "Plus de nouvelles, or +2 par saison" },
      wolfValley: { name: "Vallée des loups", hint: "Sécurité -10, bonne chasse" },
      harsh: { name: "Pays froid", hint: "Bois de chauffage +1 en hiver, +30 au score final" },
      lucky: { name: "Village chanceux", hint: "Les choix risqués réussissent 10 points plus souvent" },
    },
    weather: {
      clear: { name: "Ciel clair", hint: "Rien de particulier" },
      rain: { name: "Pluie", hint: "Champs +25 %" },
      wind: { name: "Vent", hint: "Bois +20 %" },
      heat: { name: "Canicule", hint: "Champs -20 %, fatigue +3" },
      storm: { name: "Tempête", hint: "Camps de bûcherons -50 %, champs -10 %" },
      fog: { name: "Brouillard", hint: "Chasse -2, sécurité -10" },
      snow: { name: "Neige", hint: "Chasse -2, bois de chauffage +1" },
      frost: { name: "Gel dur", hint: "Bois de chauffage +2" },
      mild: { name: "Hiver doux", hint: "Pas de bois de chauffage, chasse +2" },
    },
    terrain: { plain: "Terrain libre", fertile: "Terre grasse", forest: "Forêt", rock: "Rocher", water: "Eau" },
    fatigueHint: "Au-delà de 70 de fatigue, tous les ateliers produisent 30 % de moins. Un banquet, ou finir le mois sans utiliser toutes ses actions, la fait baisser.",
    commandsTitle: "Ordres du chef",
    cmd: {
      tend: { name: "Soigner les champs", hint: "Récolte +50 % ce mois-ci" },
      lumber: { name: "Couper du bois", hint: "Bois +6 à 10" },
      quarry: { name: "Extraire", hint: "Pierre +4 à 6" },
      hunt: { name: "Chasser", hint: "Nourriture +3 à 9" },
      build: { name: "Construire", hint: "Lancer un bâtiment ou +30 de travaux" },
      patrol: { name: "Patrouiller", hint: "Sécurité +10 ce mois-ci" },
      feast: { name: "Banquet", hint: "Une ration par villageois, fatigue -25" },
      explore: { name: "Explorer", hint: "On ne sait jamais. Fatigue +6" },
    },
    buildTitle: "Que construire ?",
    placeHint: "Touchez une case de la carte pour : {name}.",
    cancel: "Annuler",
    building: {
      field: { name: "Champ", hint: "Nourriture. Terre grasse +50 %, près de l’eau ou d’un puits +25 %" },
      house: { name: "Maison", hint: "2 places de plus" },
      storehouse: { name: "Entrepôt", hint: "Stockage +60" },
      lumberCamp: { name: "Camp de bûcherons", hint: "Bois chaque mois, plus avec plus de forêt autour" },
      quarry: { name: "Carrière", hint: "Pierre chaque mois, plus avec plus de rochers autour" },
      hut: { name: "Cabane de chasse", hint: "Nourriture, même en hiver" },
      kitchen: { name: "Cuisine", hint: "Nourriture consommée -20 %, fatigue -3 par mois" },
      well: { name: "Puits", hint: "Champs voisins +25 %" },
      watchtower: { name: "Tour de guet", hint: "Sécurité +15, ou +25 avec un garde" },
      market: { name: "Marché", hint: "3 d’or par mois, +1 par maison voisine" },
      smithy: { name: "Forge", hint: "Tous les ateliers +20 %" },
      hall: { name: "Salle commune", hint: "Une action de plus par mois, +40 au score final" },
    },
    nearForest: "Doit toucher une forêt",
    nearRock: "Doit toucher un rocher",
    project: "En chantier : {name} {p}/{n}",
    eventTitle: "Nouvelles du mois",
    needEvent: "Décidez d’abord des nouvelles du mois.",
    events: {
      drought: { title: "Sécheresse", text: "Pas de pluie, les champs se dessèchent.", choices: ["Porter de l’eau", "Laisser faire"] },
      bumper: { title: "Beau temps", text: "Le temps est clément et les cultures poussent bien.", choices: ["Parfait"] },
      trader: { title: "Marchand ambulant", text: "Un marchand s’est installé à l’entrée du village.", choices: ["Vendre du bois", "Acheter de la nourriture", "Le laisser repartir"] },
      wolves: { title: "Loups", text: "Les hurlements se rapprochent chaque nuit.", choices: ["Monter la garde", "Se cacher"] },
      coldSnap: { title: "Vague de froid", text: "Les nuits sont devenues glaciales.", choices: ["Brûler plus de bois", "Tenir bon"] },
      festival: { title: "Jour de fête", text: "Les villageois aimeraient un jour de repos.", choices: ["Faire la fête", "Remettre à plus tard"] },
      sickness: { title: "Maladie", text: "De plus en plus de villageois toussent.", choices: ["Les laisser se reposer", "Acheter des remèdes"] },
      traveler: { title: "Un voyageur", text: "Un voyageur de passage cherche où loger.", choices: ["L’accueillir", "Lui indiquer la route"] },
      gambler: { title: "Un joueur", text: "Un joueur de passage propose une partie.", choices: ["Parier", "Refuser"] },
      ruins: { title: "Vieilles fondations", text: "On a trouvé de vieilles fondations à l’orée du bois.", choices: ["Creuser", "Ne pas y toucher"] },
      bees: { title: "Une ruche", text: "Une grosse ruche pend à un arbre.", choices: ["Prendre le miel", "La laisser"] },
      storm: { title: "Avis de tempête", text: "Le ciel n’annonce rien de bon.", choices: ["Renforcer les toits", "Laisser passer"] },
      bandits: { title: "Brigands", text: "Une bande de brigands réclame un péage.", choices: ["Payer", "Leur tenir tête"] },
      fishRun: { title: "Banc de poissons", text: "Le ruisseau grouille de poissons.", choices: ["Tout le monde à la pêche", "Laisser passer"] },
      lostChild: { title: "Enfant perdu", text: "Un enfant du village voisin s’est perdu dans les bois.", choices: ["Partir à sa recherche", "Fermer les yeux"] },
      caravan: { title: "Une caravane", text: "Une grande caravane fait halte au village.", choices: ["Vendre de la nourriture", "Acheter de la pierre", "Regarder seulement"] },
      fire: { title: "Au feu !", text: "Une remise a pris feu.", choices: ["Tout le monde l’éteint", "Laisser brûler"] },
      heavySnow: { title: "Grosse neige", text: "La neige est tombée jusqu’à la taille en une nuit.", choices: ["Déblayer", "Attendre le dégel"] },
      shootingStar: { title: "Étoiles filantes", text: "Le ciel de nuit est plein d’étoiles filantes.", choices: ["Regarder ensemble"] },
      rats: { title: "Des rats", text: "Des rats sont entrés dans le grenier.", choices: ["Poser des pièges", "Ne rien faire"] },
      healer: { title: "Guérisseur de passage", text: "Un guérisseur habile reste une nuit.", choices: ["Tout le monde consulte", "Le laisser repartir"] },
      mushrooms: { title: "Champignons", text: "Les bois sont pleins de champignons inconnus.", choices: ["Les cueillir et les manger", "Les laisser"] },
      taxman: { title: "Impôts", text: "Le percepteur est arrivé.", choices: ["Payer", "Plaider sa cause"] },
      family: { title: "Une famille", text: "Une famille cherche où s’installer.", choices: ["Les accueillir", "Leur indiquer la route"] },
    },
    outcome: { odds: "{n} % de chances de réussite", safe: "Réussit à partir de {n} de sécurité", otherwise: "En cas d’échec", harvest: "récolte {n} % ce mois-ci" },
    endMonth: "Terminer le mois",
    reportTitle: "Le mois dernier",
    reportEmpty: "Aucun mois n’est encore passé.",
    report: {
      weather: "Météo : {name}", tired: "Tout le monde était épuisé, la production a baissé", made: "Ateliers : {name} +{n}", idle: "Villageois sans travail : {n}",
      built: "{name} : terminé", eaten: "Nourriture consommée : {n}", hungry: "Il n’y avait pas assez à manger", left: "{name} a quitté le village",
      firewood: "Bois de chauffage : bois {n}", cold: "Pas de bois de chauffage, un mois glacial", newcomer: "Un nouveau villageois est arrivé", tax: "Or de la saison : +{n}",
      tended: "Les champs ont été soignés", patrolled: "Le village a été surveillé", nothing: "On n’a rien trouvé", treasure: "Un trésor enfoui !",
      progress: "{name} : travaux {n}", good: "Ça s’est bien passé", bad: "Ça s’est mal passé", harvestMod: "Récolte {n} % ce mois-ci", delta: "{name} {n}",
    },
    tile: { title: "Case choisie", empty: "Rien ici", worker: "Ouvrier", noWorker: "Personne n’y travaille, c’est à l’arrêt", none: "Personne", send: "Envoyer" },
    peopleTitle: "Villageois",
    idle: "Sans travail",
    auto: "Envoyer les inoccupés vers les ateliers vides",
    trait: {
      diligent: { name: "Travailleur", hint: "Travail +25 %" },
      strong: { name: "Costaud", hint: "Camp de bûcherons et carrière +50 %" },
      greenThumb: { name: "Main verte", hint: "Champs +50 %" },
      glutton: { name: "Gros mangeur", hint: "Mange 3 de nourriture" },
      frugal: { name: "Petit mangeur", hint: "Ne mange que 1 de nourriture" },
      lazy: { name: "Paresseux", hint: "Travail -25 %" },
      brave: { name: "Courageux", hint: "Sécurité +5" },
      merchant: { name: "Commerçant", hint: "Marché +50 %, or +1 par saison" },
    },
    names: ["Aubin", "Berthe", "Colin", "Denise", "Émile", "Flore", "Gaston", "Hélène", "Isidore", "Jeanne", "Léon", "Margot", "Nestor", "Odile", "Perrin", "Rose", "Simon", "Thérèse", "Urbain", "Violette", "Yvon", "Zélie", "Basile", "Lucie"],
    overTitle: "Trois ans ont passé",
    score: "Score",
    best: "Meilleur score",
    grades: ["Petit village", "Beau village", "Village renommé"],
    again: "Fonder un nouveau village",
    againConfirm: "Effacer ce village et recommencer ?",
    save: {
      title: "Code de sauvegarde",
      note: "Votre village est enregistré automatiquement dans ce navigateur. Copiez le code et collez-le sur un autre appareil pour continuer. Rien n’est envoyé à un serveur.",
      copy: "Copier le code", copied: "Copié", paste: "Collez un code ici", load: "Charger",
      bad: "Ce code est illisible. Votre village n’a pas été modifié.", loaded: "Village chargé",
    },
  },
  es: {
    title: "Doce meses, una aldea",
    sub: "Gestión de aldea mes a mes",
    intro: "El mapa, el carácter de la aldea, los aldeanos, el tiempo y las noticias cambian en cada partida. Tres acciones al mes, tres años (36 meses).",
    date: "Año {y}, mes {m}",
    seasons: ["Primavera", "Verano", "Otoño", "Invierno"],
    progress: "Mes {n} de 36",
    res: { food: "Comida", wood: "Madera", stone: "Piedra", gold: "Oro", pop: "Aldeanos", fatigue: "Cansancio", safety: "Seguridad", ap: "Acciones restantes" },
    villageTrait: {
      fertile: { name: "Tierra fértil", hint: "Campos +15 %" },
      deepWoods: { name: "Bosque profundo", hint: "Madera +25 %" },
      stony: { name: "Suelo pedregoso", hint: "Piedra +25 %" },
      crossroads: { name: "Cruce de caminos", hint: "Llegan más noticias, oro +2 por temporada" },
      wolfValley: { name: "Valle de lobos", hint: "Seguridad -10, buena caza" },
      harsh: { name: "Tierra fría", hint: "Leña +1 en invierno, +30 puntos al final" },
      lucky: { name: "Aldea con suerte", hint: "Las apuestas salen bien 10 puntos más a menudo" },
    },
    weather: {
      clear: { name: "Despejado", hint: "Nada especial" },
      rain: { name: "Lluvia", hint: "Campos +25 %" },
      wind: { name: "Viento", hint: "Madera +20 %" },
      heat: { name: "Ola de calor", hint: "Campos -20 %, cansancio +3" },
      storm: { name: "Tormenta", hint: "Campamentos madereros -50 %, campos -10 %" },
      fog: { name: "Niebla", hint: "Caza -2, seguridad -10" },
      snow: { name: "Nieve", hint: "Caza -2, leña +1" },
      frost: { name: "Helada", hint: "Leña +2" },
      mild: { name: "Invierno suave", hint: "No hace falta leña, caza +2" },
    },
    terrain: { plain: "Terreno libre", fertile: "Tierra fértil", forest: "Bosque", rock: "Roca", water: "Agua" },
    fatigueHint: "Por encima de 70 de cansancio, todos los talleres producen un 30 % menos. Un banquete, o terminar el mes con acciones sin usar, lo reduce.",
    commandsTitle: "Órdenes del jefe",
    cmd: {
      tend: { name: "Cuidar los campos", hint: "Cosecha +50 % este mes" },
      lumber: { name: "Talar", hint: "Madera +6 a 10" },
      quarry: { name: "Picar piedra", hint: "Piedra +4 a 6" },
      hunt: { name: "Cazar", hint: "Comida +3 a 9" },
      build: { name: "Construir", hint: "Empezar un edificio o +30 de obra" },
      patrol: { name: "Patrullar", hint: "Seguridad +10 este mes" },
      feast: { name: "Banquete", hint: "Una ración por aldeano, cansancio -25" },
      explore: { name: "Explorar", hint: "Nunca se sabe. Cansancio +6" },
    },
    buildTitle: "¿Qué construimos?",
    placeHint: "Toca una casilla del mapa para: {name}.",
    cancel: "Cancelar",
    building: {
      field: { name: "Campo", hint: "Comida. Tierra fértil +50 %, junto a agua o pozo +25 %" },
      house: { name: "Casa", hint: "Sitio para 2 aldeanos más" },
      storehouse: { name: "Almacén", hint: "Límite de almacenaje +60" },
      lumberCamp: { name: "Campamento maderero", hint: "Madera cada mes, más con más bosque alrededor" },
      quarry: { name: "Cantera", hint: "Piedra cada mes, más con más roca alrededor" },
      hut: { name: "Cabaña de caza", hint: "Comida, también en invierno" },
      kitchen: { name: "Cocina", hint: "Comida consumida -20 %, cansancio -3 al mes" },
      well: { name: "Pozo", hint: "Campos vecinos +25 %" },
      watchtower: { name: "Torre de vigía", hint: "Seguridad +15, o +25 con un guardia" },
      market: { name: "Mercado", hint: "3 de oro al mes, +1 por cada casa vecina" },
      smithy: { name: "Herrería", hint: "Todos los talleres +20 %" },
      hall: { name: "Casa comunal", hint: "Una acción más al mes, +40 puntos al final" },
    },
    nearForest: "Debe estar junto a un bosque",
    nearRock: "Debe estar junto a una roca",
    project: "En obra: {name} {p}/{n}",
    eventTitle: "Noticias del mes",
    needEvent: "Primero decide las noticias de este mes.",
    events: {
      drought: { title: "Sequía", text: "No llueve y los campos se están secando.", choices: ["Acarrear agua", "Dejarlo estar"] },
      bumper: { title: "Buen tiempo", text: "El tiempo acompaña y los cultivos crecen bien.", choices: ["Estupendo"] },
      trader: { title: "Mercader ambulante", text: "Un mercader ha montado su puesto a la entrada de la aldea.", choices: ["Vender madera", "Comprar comida", "Dejar que siga"] },
      wolves: { title: "Lobos", text: "Los aullidos se acercan cada noche.", choices: ["Hacer guardia", "Esconderse"] },
      coldSnap: { title: "Ola de frío", text: "Las noches se han vuelto heladas.", choices: ["Quemar más leña", "Aguantar"] },
      festival: { title: "Día de fiesta", text: "Los aldeanos quieren un día de descanso.", choices: ["Celebrar la fiesta", "Dejarlo para otra vez"] },
      sickness: { title: "Enfermedad", text: "Cada vez más aldeanos tosen.", choices: ["Dejar que descansen", "Comprar medicinas"] },
      traveler: { title: "Un viajero", text: "Un viajero de paso busca dónde quedarse.", choices: ["Acogerlo", "Indicarle el camino"] },
      gambler: { title: "Un jugador", text: "Un jugador errante propone una partida.", choices: ["Apostar", "Negarse"] },
      ruins: { title: "Viejos cimientos", text: "Han aparecido unos cimientos viejos al borde del bosque.", choices: ["Excavar", "No tocarlos"] },
      bees: { title: "Una colmena", text: "Una gran colmena cuelga de un árbol.", choices: ["Sacar la miel", "Dejarla en paz"] },
      storm: { title: "Aviso de tormenta", text: "El cielo no pinta bien.", choices: ["Reforzar los tejados", "Aguantar el temporal"] },
      bandits: { title: "Bandidos", text: "Una banda de ladrones exige un peaje.", choices: ["Pagar", "Plantarles cara"] },
      fishRun: { title: "Banco de peces", text: "El arroyo está lleno de peces.", choices: ["Todos a pescar", "Dejarlo pasar"] },
      lostChild: { title: "Un niño perdido", text: "Un niño de la aldea vecina se ha perdido en el bosque.", choices: ["Salir a buscarlo", "Mirar a otro lado"] },
      caravan: { title: "Una caravana", text: "Una gran caravana ha parado en la aldea.", choices: ["Vender comida", "Comprar piedra", "Solo mirar"] },
      fire: { title: "¡Fuego!", text: "Se ha incendiado un cobertizo.", choices: ["Todos a apagarlo", "Dejar que arda"] },
      heavySnow: { title: "Gran nevada", text: "La nieve llegó a la cintura en una noche.", choices: ["Quitar la nieve", "Esperar al deshielo"] },
      shootingStar: { title: "Estrellas fugaces", text: "El cielo nocturno se llenó de estrellas fugaces.", choices: ["Mirarlas juntos"] },
      rats: { title: "Ratas", text: "Han entrado ratas en el granero.", choices: ["Poner trampas", "No hacer nada"] },
      healer: { title: "Curandero de paso", text: "Un curandero hábil se queda una noche.", choices: ["Que atienda a todos", "Dejar que siga"] },
      mushrooms: { title: "Setas", text: "El bosque está lleno de setas desconocidas.", choices: ["Recogerlas y comerlas", "Dejarlas"] },
      taxman: { title: "Impuestos", text: "Ha llegado el recaudador.", choices: ["Pagar", "Suplicar"] },
      family: { title: "Una familia", text: "Una familia busca dónde vivir.", choices: ["Acogerlos", "Indicarles el camino"] },
    },
    outcome: { odds: "{n} % de probabilidad de éxito", safe: "Sale bien con seguridad {n} o más", otherwise: "Si sale mal", harvest: "cosecha {n} % este mes" },
    endMonth: "Terminar el mes",
    reportTitle: "El mes pasado",
    reportEmpty: "Todavía no ha pasado ningún mes.",
    report: {
      weather: "Tiempo: {name}", tired: "Todos estaban agotados y se produjo menos", made: "Talleres: {name} +{n}", idle: "Aldeanos sin trabajo: {n}",
      built: "{name}: terminado", eaten: "Comida consumida: {n}", hungry: "No hubo comida suficiente", left: "{name} se fue de la aldea",
      firewood: "Leña: madera {n}", cold: "Sin leña, un mes de frío", newcomer: "Llegó un nuevo aldeano", tax: "Oro de la temporada: +{n}",
      tended: "Se cuidaron los campos", patrolled: "Se patrulló la aldea", nothing: "No se encontró nada", treasure: "¡Un tesoro enterrado!",
      progress: "{name}: obra {n}", good: "Salió bien", bad: "Salió mal", harvestMod: "Cosecha {n} % este mes", delta: "{name} {n}",
    },
    tile: { title: "Casilla elegida", empty: "Aquí no hay nada", worker: "Trabajador", noWorker: "Nadie trabaja aquí, así que está parado", none: "Nadie", send: "Enviar" },
    peopleTitle: "Aldeanos",
    idle: "Sin trabajo",
    auto: "Enviar a los desocupados a los talleres vacíos",
    trait: {
      diligent: { name: "Trabajador", hint: "Trabajo +25 %" },
      strong: { name: "Fuerte", hint: "Campamento maderero y cantera +50 %" },
      greenThumb: { name: "Buen labrador", hint: "Campos +50 %" },
      glutton: { name: "Comilón", hint: "Come 3 de comida" },
      frugal: { name: "De poco comer", hint: "Solo come 1 de comida" },
      lazy: { name: "Perezoso", hint: "Trabajo -25 %" },
      brave: { name: "Valiente", hint: "Seguridad +5" },
      merchant: { name: "Comerciante", hint: "Mercado +50 %, oro +1 por temporada" },
    },
    names: ["Anselmo", "Brígida", "Cosme", "Dorotea", "Eladio", "Fermina", "Goyo", "Hilaria", "Isidro", "Juana", "Lázaro", "Martina", "Nicasio", "Olalla", "Paco", "Remedios", "Sancho", "Tomasa", "Ubaldo", "Vicenta", "Zacarías", "Lola", "Blas", "Rosa"],
    overTitle: "Han pasado tres años",
    score: "Puntuación",
    best: "Mejor puntuación",
    grades: ["Aldea pequeña", "Aldea próspera", "Aldea famosa"],
    again: "Fundar una aldea nueva",
    againConfirm: "¿Borrar esta aldea y empezar de nuevo?",
    save: {
      title: "Código de guardado",
      note: "Tu aldea se guarda sola en este navegador. Copia el código y pégalo en otro dispositivo para seguir allí. No se envía nada a un servidor.",
      copy: "Copiar código", copied: "Copiado", paste: "Pega un código aquí", load: "Cargar",
      bad: "No se pudo leer ese código. Tu aldea sigue como estaba.", loaded: "Aldea cargada",
    },
  },
};
