import type { Locale } from "../../lib/i18n";
import type { BuildingId, CommandId, EventId } from "../../lib/games/village";

type Named = { name: string; hint: string };
export interface VillageCopy {
  title: string;
  sub: string;
  trial: string;
  date: string;
  seasons: [string, string, string, string];
  progress: string;
  res: { food: string; wood: string; stone: string; gold: string; pop: string; fatigue: string; safety: string; ap: string };
  commandsTitle: string;
  cmd: Record<CommandId, Named>;
  buildTitle: string;
  buildCancel: string;
  building: Record<BuildingId, Named>;
  project: string;
  eventTitle: string;
  needEvent: string;
  events: Record<EventId, { title: string; text: string; choices: string[] }>;
  endMonth: string;
  reportTitle: string;
  reportEmpty: string;
  report: Record<string, string>;
  overTitle: string;
  score: string;
  best: string;
  grades: [string, string, string];
  again: string;
  againConfirm: string;
  save: { title: string; note: string; copy: string; copied: string; paste: string; load: string; bad: string; loaded: string };
}

export const VILLAGE_COPY: Record<Locale, VillageCopy> = {
  ko: {
    title: "작은 마을 열두 달",
    sub: "월 단위 마을 경영",
    trial: "시험판이에요. 그림 없이 규칙만 먼저 만들었어요. 한 달에 행동 세 번, 3년(36개월)을 버티며 마을을 키워 보세요.",
    date: "{y}년째 {m}월",
    seasons: ["봄", "여름", "가을", "겨울"],
    progress: "36개월 중 {n}번째 달",
    res: { food: "식량", wood: "목재", stone: "석재", gold: "금화", pop: "주민", fatigue: "피로", safety: "안전", ap: "남은 행동" },
    commandsTitle: "촌장 명령",
    cmd: {
      tend: { name: "밭일", hint: "이번 달 수확 +50%" },
      lumber: { name: "벌목", hint: "목재 +8" },
      quarry: { name: "채석", hint: "석재 +5" },
      hunt: { name: "사냥", hint: "식량 +6 (겨울 +4)" },
      build: { name: "건설", hint: "새로 짓거나 공사 +30" },
      patrol: { name: "순찰", hint: "이번 달 안전 +10" },
      feast: { name: "잔치", hint: "주민 수만큼 식량을 쓰고 피로 -25" },
    },
    buildTitle: "무엇을 지을까요?",
    buildCancel: "닫기",
    building: {
      field: { name: "밭", hint: "달마다 식량. 두 칸에 일손 한 명" },
      house: { name: "집", hint: "주민 자리 +2" },
      storehouse: { name: "창고", hint: "보관 한도 +60" },
      lumberCamp: { name: "벌목장", hint: "달마다 목재 +4" },
      quarry: { name: "채석장", hint: "달마다 석재 +3" },
      fence: { name: "울타리", hint: "안전 +20" },
    },
    project: "짓는 중: {name} {p}/{n}",
    eventTitle: "이번 달 소식",
    needEvent: "먼저 이번 달 소식을 정해 주세요.",
    events: {
      drought: { title: "가뭄", text: "비가 오지 않아 밭이 말라 가요.", choices: ["물을 길어 온다 (피로 +15)", "그냥 둔다 (이번 달 수확 -40%)"] },
      bumper: { title: "풍년", text: "날씨가 도와서 작물이 잘 자라요.", choices: ["좋아요 (이번 달 수확 +50%)"] },
      trader: { title: "떠돌이 상인", text: "상인이 마을 어귀에 짐을 풀었어요.", choices: ["목재 10을 판다 (금화 +8)", "식량 12를 산다 (금화 -8)", "그냥 보낸다"] },
      wolves: { title: "늑대", text: "밤마다 늑대 울음이 가까워져요.", choices: ["맞선다 (안전 50 이상이면 피로 +5, 아니면 피로 +20·식량 -6)", "숨는다 (식량 -12)"] },
      coldSnap: { title: "한파", text: "유난히 추운 밤이 이어져요.", choices: ["장작을 더 땐다 (목재 -6)", "버틴다 (피로 +20)"] },
      festival: { title: "마을 잔칫날", text: "주민들이 하루 쉬어 가자고 해요.", choices: ["잔치를 연다 (식량 -8, 피로 -30)", "다음으로 미룬다"] },
      sickness: { title: "돌림병", text: "기침하는 주민이 늘었어요.", choices: ["쉬게 한다 (피로 +20)", "약을 산다 (금화 -6)"] },
      traveler: { title: "나그네", text: "지나가던 나그네가 머물 곳을 찾아요.", choices: ["주민으로 맞는다 (주민 +1, 빈 자리가 있어야 해요)", "길을 알려 준다 (금화 +5)"] },
    },
    endMonth: "이번 달 마치기",
    reportTitle: "지난달 결과",
    reportEmpty: "아직 지난달이 없어요.",
    report: {
      harvest: "밭에서 식량 +{n}", wood: "벌목장에서 목재 +{n}", stone: "채석장에서 석재 +{n}", tired: "모두 지쳐서 생산이 줄었어요",
      built: "{name} 완성", eaten: "먹은 식량 -{n}", hungry: "식량이 모자라 굶었어요", left: "주민 한 명이 떠났어요",
      firewood: "장작으로 목재 -{n}", cold: "장작이 없어 추위에 떨었어요", newcomer: "새 주민이 왔어요", tax: "철마다 모은 금화 +{n}",
    },
    overTitle: "3년이 지났어요",
    score: "점수",
    best: "최고 점수",
    grades: ["작은 마을", "번듯한 마을", "이름난 마을"],
    again: "새 마을 시작",
    againConfirm: "지금 마을을 지우고 새로 시작할까요?",
    save: {
      title: "세이브 코드",
      note: "이 브라우저에 자동으로 저장돼요. 코드를 복사해 다른 기기에 붙여 넣으면 이어서 할 수 있어요. 서버로는 보내지 않아요.",
      copy: "코드 복사", copied: "복사했어요", paste: "코드를 여기에 붙여 넣으세요", load: "불러오기",
      bad: "읽을 수 없는 코드예요. 지금 마을은 그대로 두었어요.", loaded: "마을을 불러왔어요",
    },
  },
  en: {
    title: "Twelve Months, One Village",
    sub: "Month-by-month village sim",
    trial: "This is a trial build: rules first, no art yet. You get three actions a month. Keep the village going for three years (36 months).",
    date: "Year {y}, month {m}",
    seasons: ["Spring", "Summer", "Autumn", "Winter"],
    progress: "Month {n} of 36",
    res: { food: "Food", wood: "Wood", stone: "Stone", gold: "Gold", pop: "Villagers", fatigue: "Fatigue", safety: "Safety", ap: "Actions left" },
    commandsTitle: "Chief's orders",
    cmd: {
      tend: { name: "Tend fields", hint: "Harvest +50% this month" },
      lumber: { name: "Cut wood", hint: "Wood +8" },
      quarry: { name: "Quarry", hint: "Stone +5" },
      hunt: { name: "Hunt", hint: "Food +6 (+4 in winter)" },
      build: { name: "Build", hint: "Start a building or add 30 work" },
      patrol: { name: "Patrol", hint: "Safety +10 this month" },
      feast: { name: "Feast", hint: "Spend food per villager, fatigue -25" },
    },
    buildTitle: "What should we build?",
    buildCancel: "Close",
    building: {
      field: { name: "Field", hint: "Food every month. One worker per two fields" },
      house: { name: "House", hint: "Room for 2 more villagers" },
      storehouse: { name: "Storehouse", hint: "Storage limit +60" },
      lumberCamp: { name: "Lumber camp", hint: "Wood +4 every month" },
      quarry: { name: "Quarry pit", hint: "Stone +3 every month" },
      fence: { name: "Fence", hint: "Safety +20" },
    },
    project: "Building: {name} {p}/{n}",
    eventTitle: "This month's news",
    needEvent: "Decide this month's news first.",
    events: {
      drought: { title: "Drought", text: "No rain, and the fields are drying out.", choices: ["Carry water (fatigue +15)", "Let it be (harvest -40% this month)"] },
      bumper: { title: "Good weather", text: "The weather is kind and the crops are thriving.", choices: ["Lovely (harvest +50% this month)"] },
      trader: { title: "Travelling trader", text: "A trader has set up at the edge of the village.", choices: ["Sell 10 wood (gold +8)", "Buy 12 food (gold -8)", "Send them on"] },
      wolves: { title: "Wolves", text: "The howling gets closer every night.", choices: ["Stand guard (fatigue +5 at safety 50 or more, otherwise fatigue +20 and food -6)", "Hide (food -12)"] },
      coldSnap: { title: "Cold snap", text: "The nights have turned bitterly cold.", choices: ["Burn more wood (wood -6)", "Tough it out (fatigue +20)"] },
      festival: { title: "Village feast day", text: "The villagers would like a day off.", choices: ["Hold the feast (food -8, fatigue -30)", "Put it off"] },
      sickness: { title: "Sickness", text: "More villagers are coughing.", choices: ["Let them rest (fatigue +20)", "Buy medicine (gold -6)"] },
      traveler: { title: "A traveller", text: "A passing traveller is looking for a place to stay.", choices: ["Welcome them (villagers +1, needs a free bed)", "Point the way (gold +5)"] },
    },
    endMonth: "End the month",
    reportTitle: "Last month",
    reportEmpty: "No month has passed yet.",
    report: {
      harvest: "Fields: food +{n}", wood: "Lumber camp: wood +{n}", stone: "Quarry pit: stone +{n}", tired: "Everyone was worn out, so less got done",
      built: "{name} finished", eaten: "Food eaten: -{n}", hungry: "There was not enough food", left: "A villager left",
      firewood: "Firewood: wood -{n}", cold: "No firewood, a cold month", newcomer: "A new villager arrived", tax: "Season's gold: +{n}",
    },
    overTitle: "Three years have passed",
    score: "Score",
    best: "Best score",
    grades: ["Small village", "Proper village", "Famous village"],
    again: "Start a new village",
    againConfirm: "Erase this village and start again?",
    save: {
      title: "Save code",
      note: "Your village is saved in this browser automatically. Copy the code and paste it on another device to carry on there. Nothing is sent to a server.",
      copy: "Copy code", copied: "Copied", paste: "Paste a code here", load: "Load",
      bad: "That code could not be read. Your village was left as it is.", loaded: "Village loaded",
    },
  },
  ja: {
    title: "小さな村の十二か月",
    sub: "月ごとの村づくり",
    trial: "試作版です。絵はまだなく、ルールだけ先に作りました。1か月に行動は3回。3年(36か月)のあいだ村を育ててみてください。",
    date: "{y}年目 {m}月",
    seasons: ["春", "夏", "秋", "冬"],
    progress: "36か月中 {n}か月目",
    res: { food: "食料", wood: "木材", stone: "石材", gold: "金貨", pop: "村人", fatigue: "疲れ", safety: "安全", ap: "残り行動" },
    commandsTitle: "村長の指示",
    cmd: {
      tend: { name: "畑仕事", hint: "今月の収穫 +50%" },
      lumber: { name: "伐採", hint: "木材 +8" },
      quarry: { name: "採石", hint: "石材 +5" },
      hunt: { name: "狩り", hint: "食料 +6(冬は +4)" },
      build: { name: "建設", hint: "新しく建てる、または工事 +30" },
      patrol: { name: "見回り", hint: "今月の安全 +10" },
      feast: { name: "宴", hint: "村人の数だけ食料を使い、疲れ -25" },
    },
    buildTitle: "何を建てますか？",
    buildCancel: "閉じる",
    building: {
      field: { name: "畑", hint: "毎月食料。2面につき働き手1人" },
      house: { name: "家", hint: "村人の枠 +2" },
      storehouse: { name: "倉庫", hint: "保管上限 +60" },
      lumberCamp: { name: "伐採場", hint: "毎月 木材 +4" },
      quarry: { name: "採石場", hint: "毎月 石材 +3" },
      fence: { name: "柵", hint: "安全 +20" },
    },
    project: "建設中: {name} {p}/{n}",
    eventTitle: "今月の知らせ",
    needEvent: "先に今月の知らせを決めてください。",
    events: {
      drought: { title: "日照り", text: "雨が降らず、畑が乾いてきました。", choices: ["水をくんでくる(疲れ +15)", "そのままにする(今月の収穫 -40%)"] },
      bumper: { title: "豊作", text: "天気に恵まれて作物がよく育っています。", choices: ["よかった(今月の収穫 +50%)"] },
      trader: { title: "旅の商人", text: "商人が村の入り口で荷をほどきました。", choices: ["木材10を売る(金貨 +8)", "食料12を買う(金貨 -8)", "見送る"] },
      wolves: { title: "オオカミ", text: "夜ごとに遠吠えが近づいてきます。", choices: ["立ち向かう(安全50以上なら疲れ +5、未満なら疲れ +20・食料 -6)", "隠れる(食料 -12)"] },
      coldSnap: { title: "寒波", text: "ひときわ寒い夜が続いています。", choices: ["薪を多くたく(木材 -6)", "がまんする(疲れ +20)"] },
      festival: { title: "村の祭りの日", text: "村人たちが一日休みたいと言っています。", choices: ["祭りを開く(食料 -8、疲れ -30)", "また今度にする"] },
      sickness: { title: "はやり病", text: "せきをする村人が増えました。", choices: ["休ませる(疲れ +20)", "薬を買う(金貨 -6)"] },
      traveler: { title: "旅人", text: "通りがかりの旅人が泊まる場所を探しています。", choices: ["村人として迎える(村人 +1、空きが必要です)", "道を教える(金貨 +5)"] },
    },
    endMonth: "今月を終える",
    reportTitle: "先月の結果",
    reportEmpty: "まだ先月はありません。",
    report: {
      harvest: "畑から食料 +{n}", wood: "伐採場から木材 +{n}", stone: "採石場から石材 +{n}", tired: "みんな疲れて生産が減りました",
      built: "{name}が完成", eaten: "食べた食料 -{n}", hungry: "食料が足りず飢えました", left: "村人が1人去りました",
      firewood: "薪として木材 -{n}", cold: "薪がなく寒さに震えました", newcomer: "新しい村人が来ました", tax: "季節ごとの金貨 +{n}",
    },
    overTitle: "3年がたちました",
    score: "スコア",
    best: "ベストスコア",
    grades: ["小さな村", "立派な村", "名の知れた村"],
    again: "新しい村を始める",
    againConfirm: "今の村を消して最初から始めますか？",
    save: {
      title: "セーブコード",
      note: "このブラウザーに自動で保存されます。コードをコピーして別の端末に貼り付けると続きができます。サーバーには送信しません。",
      copy: "コードをコピー", copied: "コピーしました", paste: "ここにコードを貼り付けてください", load: "読み込む",
      bad: "読み取れないコードです。今の村はそのままです。", loaded: "村を読み込みました",
    },
  },
  zh: {
    title: "小村庄的十二个月",
    sub: "按月经营的村庄",
    trial: "这是试玩版：先做了规则，还没有画面。每个月可以行动三次，试着把村庄经营满三年(36个月)。",
    date: "第{y}年 {m}月",
    seasons: ["春", "夏", "秋", "冬"],
    progress: "36个月中的第{n}个月",
    res: { food: "粮食", wood: "木材", stone: "石材", gold: "金币", pop: "村民", fatigue: "疲劳", safety: "安全", ap: "剩余行动" },
    commandsTitle: "村长指令",
    cmd: {
      tend: { name: "照料田地", hint: "本月收成 +50%" },
      lumber: { name: "伐木", hint: "木材 +8" },
      quarry: { name: "采石", hint: "石材 +5" },
      hunt: { name: "打猎", hint: "粮食 +6(冬季 +4)" },
      build: { name: "建造", hint: "新建，或工程 +30" },
      patrol: { name: "巡逻", hint: "本月安全 +10" },
      feast: { name: "宴会", hint: "按村民人数消耗粮食，疲劳 -25" },
    },
    buildTitle: "要建什么？",
    buildCancel: "关闭",
    building: {
      field: { name: "田地", hint: "每月产粮。每两块需要一名劳力" },
      house: { name: "房屋", hint: "村民名额 +2" },
      storehouse: { name: "仓库", hint: "储存上限 +60" },
      lumberCamp: { name: "伐木场", hint: "每月木材 +4" },
      quarry: { name: "采石场", hint: "每月石材 +3" },
      fence: { name: "围栏", hint: "安全 +20" },
    },
    project: "建造中：{name} {p}/{n}",
    eventTitle: "本月消息",
    needEvent: "请先决定本月的消息。",
    events: {
      drought: { title: "干旱", text: "一直不下雨，田地快干了。", choices: ["去挑水(疲劳 +15)", "不管它(本月收成 -40%)"] },
      bumper: { title: "丰收", text: "天气帮忙，庄稼长得很好。", choices: ["太好了(本月收成 +50%)"] },
      trader: { title: "行商", text: "一位商人在村口摆开了货物。", choices: ["卖出10木材(金币 +8)", "买入12粮食(金币 -8)", "让他走"] },
      wolves: { title: "狼群", text: "每晚的狼嚎越来越近。", choices: ["迎战(安全50以上疲劳 +5，否则疲劳 +20、粮食 -6)", "躲起来(粮食 -12)"] },
      coldSnap: { title: "寒潮", text: "夜里格外寒冷。", choices: ["多烧柴(木材 -6)", "硬撑(疲劳 +20)"] },
      festival: { title: "村里的节日", text: "村民们想休息一天。", choices: ["办宴会(粮食 -8，疲劳 -30)", "下次再说"] },
      sickness: { title: "流行病", text: "咳嗽的村民变多了。", choices: ["让他们休息(疲劳 +20)", "买药(金币 -6)"] },
      traveler: { title: "旅人", text: "一位路过的旅人在找落脚的地方。", choices: ["收留为村民(村民 +1，需要有空位)", "给他指路(金币 +5)"] },
    },
    endMonth: "结束本月",
    reportTitle: "上个月的结果",
    reportEmpty: "还没有过去的月份。",
    report: {
      harvest: "田地产粮 +{n}", wood: "伐木场木材 +{n}", stone: "采石场石材 +{n}", tired: "大家太累，产量减少了",
      built: "{name}建成", eaten: "消耗粮食 -{n}", hungry: "粮食不够，挨饿了", left: "一位村民离开了",
      firewood: "烧柴消耗木材 -{n}", cold: "没有柴火，冻了一个月", newcomer: "来了一位新村民", tax: "当季金币 +{n}",
    },
    overTitle: "三年过去了",
    score: "分数",
    best: "最高分",
    grades: ["小村庄", "像样的村庄", "出名的村庄"],
    again: "开始新村庄",
    againConfirm: "要清除当前村庄并重新开始吗？",
    save: {
      title: "存档码",
      note: "村庄会自动保存在此浏览器中。复制存档码并粘贴到另一台设备上，就能接着玩。不会发送到服务器。",
      copy: "复制存档码", copied: "已复制", paste: "在这里粘贴存档码", load: "读取",
      bad: "无法读取这个存档码。当前村庄保持不变。", loaded: "已读取村庄",
    },
  },
  fr: {
    title: "Douze mois, un village",
    sub: "Gestion de village mois par mois",
    trial: "Version d’essai : les règles d’abord, sans illustrations pour l’instant. Vous avez trois actions par mois. Faites tenir le village pendant trois ans (36 mois).",
    date: "Année {y}, mois {m}",
    seasons: ["Printemps", "Été", "Automne", "Hiver"],
    progress: "Mois {n} sur 36",
    res: { food: "Nourriture", wood: "Bois", stone: "Pierre", gold: "Or", pop: "Villageois", fatigue: "Fatigue", safety: "Sécurité", ap: "Actions restantes" },
    commandsTitle: "Ordres du chef",
    cmd: {
      tend: { name: "Soigner les champs", hint: "Récolte +50 % ce mois-ci" },
      lumber: { name: "Couper du bois", hint: "Bois +8" },
      quarry: { name: "Extraire", hint: "Pierre +5" },
      hunt: { name: "Chasser", hint: "Nourriture +6 (+4 en hiver)" },
      build: { name: "Construire", hint: "Lancer un bâtiment ou +30 de travaux" },
      patrol: { name: "Patrouiller", hint: "Sécurité +10 ce mois-ci" },
      feast: { name: "Banquet", hint: "Une ration par villageois, fatigue -25" },
    },
    buildTitle: "Que construire ?",
    buildCancel: "Fermer",
    building: {
      field: { name: "Champ", hint: "Nourriture chaque mois. Un ouvrier pour deux champs" },
      house: { name: "Maison", hint: "2 places de plus" },
      storehouse: { name: "Entrepôt", hint: "Stockage +60" },
      lumberCamp: { name: "Camp de bûcherons", hint: "Bois +4 chaque mois" },
      quarry: { name: "Carrière", hint: "Pierre +3 chaque mois" },
      fence: { name: "Palissade", hint: "Sécurité +20" },
    },
    project: "En chantier : {name} {p}/{n}",
    eventTitle: "Nouvelles du mois",
    needEvent: "Décidez d’abord des nouvelles du mois.",
    events: {
      drought: { title: "Sécheresse", text: "Pas de pluie, les champs se dessèchent.", choices: ["Porter de l’eau (fatigue +15)", "Laisser faire (récolte -40 % ce mois-ci)"] },
      bumper: { title: "Beau temps", text: "Le temps est clément et les cultures poussent bien.", choices: ["Parfait (récolte +50 % ce mois-ci)"] },
      trader: { title: "Marchand ambulant", text: "Un marchand s’est installé à l’entrée du village.", choices: ["Vendre 10 de bois (or +8)", "Acheter 12 de nourriture (or -8)", "Le laisser repartir"] },
      wolves: { title: "Loups", text: "Les hurlements se rapprochent chaque nuit.", choices: ["Monter la garde (fatigue +5 à partir de 50 de sécurité, sinon fatigue +20 et nourriture -6)", "Se cacher (nourriture -12)"] },
      coldSnap: { title: "Vague de froid", text: "Les nuits sont devenues glaciales.", choices: ["Brûler plus de bois (bois -6)", "Tenir bon (fatigue +20)"] },
      festival: { title: "Jour de fête", text: "Les villageois aimeraient un jour de repos.", choices: ["Faire la fête (nourriture -8, fatigue -30)", "Remettre à plus tard"] },
      sickness: { title: "Maladie", text: "De plus en plus de villageois toussent.", choices: ["Les laisser se reposer (fatigue +20)", "Acheter des remèdes (or -6)"] },
      traveler: { title: "Un voyageur", text: "Un voyageur de passage cherche où loger.", choices: ["L’accueillir (villageois +1, il faut une place libre)", "Lui indiquer la route (or +5)"] },
    },
    endMonth: "Terminer le mois",
    reportTitle: "Le mois dernier",
    reportEmpty: "Aucun mois n’est encore passé.",
    report: {
      harvest: "Champs : nourriture +{n}", wood: "Camp de bûcherons : bois +{n}", stone: "Carrière : pierre +{n}", tired: "Tout le monde était épuisé, la production a baissé",
      built: "{name} : terminé", eaten: "Nourriture consommée : -{n}", hungry: "Il n’y avait pas assez à manger", left: "Un villageois est parti",
      firewood: "Bois de chauffage : bois -{n}", cold: "Pas de bois de chauffage, un mois glacial", newcomer: "Un nouveau villageois est arrivé", tax: "Or de la saison : +{n}",
    },
    overTitle: "Trois ans ont passé",
    score: "Score",
    best: "Meilleur score",
    grades: ["Petit village", "Beau village", "Village renommé"],
    again: "Fonder un nouveau village",
    againConfirm: "Effacer ce village et recommencer ?",
    save: {
      title: "Code de sauvegarde",
      note: "Votre village est enregistré automatiquement dans ce navigateur. Copiez le code et collez-le sur un autre appareil pour continuer. Rien n’est envoyé à un serveur.",
      copy: "Copier le code", copied: "Copié", paste: "Collez un code ici", load: "Charger",
      bad: "Ce code est illisible. Votre village n’a pas été modifié.", loaded: "Village chargé",
    },
  },
  es: {
    title: "Doce meses, una aldea",
    sub: "Gestión de aldea mes a mes",
    trial: "Es una versión de prueba: primero las reglas, todavía sin ilustraciones. Tienes tres acciones al mes. Mantén la aldea durante tres años (36 meses).",
    date: "Año {y}, mes {m}",
    seasons: ["Primavera", "Verano", "Otoño", "Invierno"],
    progress: "Mes {n} de 36",
    res: { food: "Comida", wood: "Madera", stone: "Piedra", gold: "Oro", pop: "Aldeanos", fatigue: "Cansancio", safety: "Seguridad", ap: "Acciones restantes" },
    commandsTitle: "Órdenes del jefe",
    cmd: {
      tend: { name: "Cuidar los campos", hint: "Cosecha +50 % este mes" },
      lumber: { name: "Talar", hint: "Madera +8" },
      quarry: { name: "Picar piedra", hint: "Piedra +5" },
      hunt: { name: "Cazar", hint: "Comida +6 (+4 en invierno)" },
      build: { name: "Construir", hint: "Empezar un edificio o +30 de obra" },
      patrol: { name: "Patrullar", hint: "Seguridad +10 este mes" },
      feast: { name: "Banquete", hint: "Una ración por aldeano, cansancio -25" },
    },
    buildTitle: "¿Qué construimos?",
    buildCancel: "Cerrar",
    building: {
      field: { name: "Campo", hint: "Comida cada mes. Un trabajador por cada dos campos" },
      house: { name: "Casa", hint: "Sitio para 2 aldeanos más" },
      storehouse: { name: "Almacén", hint: "Límite de almacenaje +60" },
      lumberCamp: { name: "Campamento maderero", hint: "Madera +4 cada mes" },
      quarry: { name: "Cantera", hint: "Piedra +3 cada mes" },
      fence: { name: "Empalizada", hint: "Seguridad +20" },
    },
    project: "En obra: {name} {p}/{n}",
    eventTitle: "Noticias del mes",
    needEvent: "Primero decide las noticias de este mes.",
    events: {
      drought: { title: "Sequía", text: "No llueve y los campos se están secando.", choices: ["Acarrear agua (cansancio +15)", "Dejarlo estar (cosecha -40 % este mes)"] },
      bumper: { title: "Buen tiempo", text: "El tiempo acompaña y los cultivos crecen bien.", choices: ["Estupendo (cosecha +50 % este mes)"] },
      trader: { title: "Mercader ambulante", text: "Un mercader ha montado su puesto a la entrada de la aldea.", choices: ["Vender 10 de madera (oro +8)", "Comprar 12 de comida (oro -8)", "Dejar que siga su camino"] },
      wolves: { title: "Lobos", text: "Los aullidos se acercan cada noche.", choices: ["Hacer guardia (cansancio +5 con seguridad 50 o más; si no, cansancio +20 y comida -6)", "Esconderse (comida -12)"] },
      coldSnap: { title: "Ola de frío", text: "Las noches se han vuelto heladas.", choices: ["Quemar más leña (madera -6)", "Aguantar (cansancio +20)"] },
      festival: { title: "Día de fiesta", text: "Los aldeanos quieren un día de descanso.", choices: ["Celebrar la fiesta (comida -8, cansancio -30)", "Dejarlo para otra vez"] },
      sickness: { title: "Enfermedad", text: "Cada vez más aldeanos tosen.", choices: ["Dejar que descansen (cansancio +20)", "Comprar medicinas (oro -6)"] },
      traveler: { title: "Un viajero", text: "Un viajero de paso busca dónde quedarse.", choices: ["Acogerlo (aldeanos +1, hace falta una cama libre)", "Indicarle el camino (oro +5)"] },
    },
    endMonth: "Terminar el mes",
    reportTitle: "El mes pasado",
    reportEmpty: "Todavía no ha pasado ningún mes.",
    report: {
      harvest: "Campos: comida +{n}", wood: "Campamento maderero: madera +{n}", stone: "Cantera: piedra +{n}", tired: "Todos estaban agotados y se produjo menos",
      built: "{name}: terminado", eaten: "Comida consumida: -{n}", hungry: "No hubo comida suficiente", left: "Un aldeano se marchó",
      firewood: "Leña: madera -{n}", cold: "Sin leña, un mes de frío", newcomer: "Llegó un nuevo aldeano", tax: "Oro de la temporada: +{n}",
    },
    overTitle: "Han pasado tres años",
    score: "Puntuación",
    best: "Mejor puntuación",
    grades: ["Aldea pequeña", "Aldea próspera", "Aldea famosa"],
    again: "Fundar una aldea nueva",
    againConfirm: "¿Borrar esta aldea y empezar de nuevo?",
    save: {
      title: "Código de guardado",
      note: "Tu aldea se guarda sola en este navegador. Copia el código y pégalo en otro dispositivo para seguir allí. No se envía nada a un servidor.",
      copy: "Copiar código", copied: "Copiado", paste: "Pega un código aquí", load: "Cargar",
      bad: "No se pudo leer ese código. Tu aldea sigue como estaba.", loaded: "Aldea cargada",
    },
  },
};
