import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { getStreak, recordStreak, type StreakStats } from '../../lib/games/records';
import { usePrefersReducedMotion } from '../../lib/games/reduced-motion';
import { createWordle, evaluateWordleGuess, explainWordleSubmit, inputWordle, submitWordle, wordleDateSeed, type WordleMark, type WordleMode, type WordleState } from '../../lib/games/wordle';
import { clearWordleSave, loadWordleSave, storeWordleSave } from '../../lib/games/wordle-save';
import { minutesUntilNextDaily } from '../../lib/games/daily';
import { Spinner } from '../ui/spinner';

const DATA_BASE = '/data/wordle'; const ROWS = [['Q','W','E','R','T','Y','U','I','O','P'], ['A','S','D','F','G','H','J','K','L'], ['ENTER','Z','X','C','V','B','N','M','⌫']];
const localDateKey = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const formatTime = (ms: number) => `${Math.floor(ms / 60000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')}`;
const COPY = {
  ko: { subtitle:'매일 새로운 5글자 영단어 퍼즐', loading:'단어 불러오는 중…', fail:'단어 데이터를 불러오지 못했습니다', daily:'오늘의 단어', random:'무작위 연습', restored:'이전 게임을 일시정지 상태로 복원했습니다', short:'글자 수가 부족합니다', invalid:'단어 목록에 없습니다', hardFail:'확인된 글자를 그대로 써야 합니다', hard:'하드 모드', pause:'일시정지', resume:'계속하기', sound:'소리', won:'정답입니다!', lost:(w:string)=>`정답은 ${w}`, again:'다시 하기', attempts:'시도', time:'시간', streak:(s:StreakStats)=>`연승 ${s.currentStreak} · 최고 ${s.maxStreak} · ${s.won}/${s.played}승`, share:'결과 복사', correct:'정확한 위치', present:'다른 위치에 있음', absent:'단어에 없음', hint:'실제 키보드 또는 화면 자판을 사용하세요.' },
  en: { subtitle:'Daily 5-letter word puzzle', loading:'Loading words…', fail:'Failed to load word data', daily:'Daily word', random:'Random practice', restored:'Previous game restored and paused', short:'Not enough letters', invalid:'Not in word list', hardFail:'Reuse the confirmed letters.', hard:'Hard mode', pause:'Pause', resume:'Resume', sound:'Sound', won:'Correct!', lost:(w:string)=>`The word was ${w}`, again:'Play again', attempts:'Attempts', time:'Time', streak:(s:StreakStats)=>`Streak ${s.currentStreak} · Best ${s.maxStreak} · ${s.won}/${s.played} won`, share:'Copy result', correct:'Correct position', present:'Present elsewhere', absent:'Not in word', hint:'Use your physical keyboard or the keys on screen.' },
  ja: { subtitle:'毎日新しい5文字の英単語パズル', loading:'単語を読み込み中…', fail:'単語データを読み込めません', daily:'今日の単語', random:'ランダム練習', restored:'前のゲームを一時停止で復元しました', short:'文字数が足りません', invalid:'単語リストにありません', hardFail:'確定した文字を使ってください', hard:'ハードモード', pause:'一時停止', resume:'再開', sound:'サウンド', won:'正解！', lost:(w:string)=>`正解は ${w}`, again:'もう一度', attempts:'回数', time:'時間', streak:(s:StreakStats)=>`連勝 ${s.currentStreak} · 最高 ${s.maxStreak} · ${s.won}/${s.played}勝`, share:'結果をコピー', correct:'正しい位置', present:'別の位置にある', absent:'単語にない', hint:'キーボードまたは画面のキーを使用してください。' },
  zh: { subtitle:'每日5字母英文单词谜题', loading:'正在加载单词…', fail:'无法加载单词数据', daily:'每日单词', random:'随机练习', restored:'已恢复并暂停上一局', short:'字母数不足', invalid:'不在单词表中', hardFail:'必须使用已确认的字母', hard:'困难模式', pause:'暂停', resume:'继续', sound:'声音', won:'答对了！', lost:(w:string)=>`答案是 ${w}`, again:'再玩一次', attempts:'次数', time:'时间', streak:(s:StreakStats)=>`连胜 ${s.currentStreak} · 最佳 ${s.maxStreak} · ${s.won}/${s.played}胜`, share:'复制结果', correct:'位置正确', present:'在其他位置', absent:'单词中没有', hint:'请使用实体键盘或屏幕键盘。' },
  fr: { subtitle:'Mot anglais quotidien en 5 lettres', loading:'Chargement des mots…', fail:'Échec du chargement des mots', daily:'Mot du jour', random:'Entraînement aléatoire', restored:'Partie restaurée en pause', short:'Pas assez de lettres', invalid:'Absent de la liste', hardFail:'Réutilisez les lettres confirmées.', hard:'Mode difficile', pause:'Pause', resume:'Reprendre', sound:'Son', won:'Correct !', lost:(w:string)=>`Le mot était ${w}`, again:'Rejouer', attempts:'Essais', time:'Temps', streak:(s:StreakStats)=>`Série ${s.currentStreak} · Record ${s.maxStreak} · ${s.won}/${s.played} gagnées`, share:'Copier le résultat', correct:'Bonne position', present:'Présent ailleurs', absent:'Absent du mot', hint:'Utilisez le clavier physique ou les touches à l’écran.' },
  es: { subtitle:'Palabra inglesa diaria de 5 letras', loading:'Cargando palabras…', fail:'No se pudieron cargar las palabras', daily:'Palabra diaria', random:'Práctica aleatoria', restored:'Partida restaurada y pausada', short:'Faltan letras', invalid:'No está en la lista', hardFail:'Reutiliza las letras confirmadas.', hard:'Modo difícil', pause:'Pausa', resume:'Continuar', sound:'Sonido', won:'¡Correcto!', lost:(w:string)=>`La palabra era ${w}`, again:'Jugar otra vez', attempts:'Intentos', time:'Tiempo', streak:(s:StreakStats)=>`Racha ${s.currentStreak} · Mejor ${s.maxStreak} · ${s.won}/${s.played} ganadas`, share:'Copiar resultado', correct:'Posición correcta', present:'Está en otra posición', absent:'No está en la palabra', hint:'Usa el teclado físico o las teclas en pantalla.' },
};
const NEXT_COPY = {
  ko: (m:number)=>`다음 단어까지 ${Math.floor(m/60)}시간 ${m%60}분`,
  en: (m:number)=>`Next word in ${Math.floor(m/60)}h ${m%60}m`,
  ja: (m:number)=>`次の単語まで ${Math.floor(m/60)}時間${m%60}分`,
  zh: (m:number)=>`距下一单词 ${Math.floor(m/60)}小时${m%60}分`,
  fr: (m:number)=>`Prochain mot dans ${Math.floor(m/60)} h ${m%60} min`,
  es: (m:number)=>`Próxima palabra en ${Math.floor(m/60)} h ${m%60} min`,
};
const markSymbol: Record<WordleMark,string> = { correct:'✓', present:'◆', absent:'×' };
const markClass: Record<WordleMark,string> = { correct:'border-green-700 bg-green-700 text-white', present:'border-amber-500 bg-amber-400 text-slate-950', absent:'border-slate-500 bg-slate-500 text-white' };

export default function WordleGame({ locale='en' }: { locale?:string }) {
  const t = COPY[locale as keyof typeof COPY] ?? COPY.en; const nextCopy = NEXT_COPY[locale as keyof typeof NEXT_COPY] ?? NEXT_COPY.en; const reduced = usePrefersReducedMotion();
  const [targets,setTargets]=useState<string[]>([]); const [valid,setValid]=useState<Set<string>>(new Set()); const [game,setGame]=useState<WordleState|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [paused,setPaused]=useState(false); const [restored,setRestored]=useState(false); const [muted,setMuted]=useState(false); const [hard,setHard]=useState(false); const [elapsed,setElapsed]=useState(0); const [stats,setStats]=useState<StreakStats|null>(null); const [nextMinutes,setNextMinutes]=useState(()=>minutesUntilNextDaily());
  const elapsedBase=useRef(0); const startedAt=useRef<number|null>(null); const audio=useRef<AudioContext|null>(null); const recorded=useRef(false);
  const guessCount=useRef(0); const [revealedCols,setRevealedCols]=useState(5);
  const target=game && targets[game.targetIndex] ? targets[game.targetIndex].toUpperCase() : '';
  const tone=(frequency:number,duration=.07)=>{if(muted||typeof window==='undefined')return; const c=audio.current??new AudioContext();audio.current=c;const o=c.createOscillator(),g=c.createGain();o.frequency.value=frequency;g.gain.setValueAtTime(.03,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+duration);};
  const start=(mode:WordleMode)=>{if(!targets.length)return;const date=mode==='daily'?localDateKey():null;const seed=mode==='daily'?wordleDateSeed(date!):(crypto.getRandomValues?.(new Uint32Array(1))[0]??Date.now())>>>0;clearWordleSave();setGame(createWordle(seed,targets.length,mode,date));setPaused(false);setRestored(false);setElapsed(0);elapsedBase.current=0;startedAt.current=Date.now();recorded.current=false;guessCount.current=0;setRevealedCols(5);setError('');};
  useEffect(()=>{Promise.all([fetch(`${DATA_BASE}/target-words-5.json`).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<string[]>;}),fetch(`${DATA_BASE}/valid-words-5.json`).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<string[]>;})]).then(([targetWords,validWords])=>{setTargets(targetWords);setValid(new Set(validWords.map(w=>w.toUpperCase())));const saved=loadWordleSave();if(saved&&saved.state.targetCount===targetWords.length&&!(saved.state.mode==='daily'&&saved.state.dateKey!==localDateKey())){setGame(saved.state);guessCount.current=saved.state.guesses.length;setRevealedCols(5);setElapsed(saved.elapsedMs);elapsedBase.current=saved.elapsedMs;setPaused(true);setRestored(true);}else{clearWordleSave();const date=localDateKey();setGame(createWordle(wordleDateSeed(date),targetWords.length,'daily',date));guessCount.current=0;startedAt.current=Date.now();}setLoading(false);}).catch(()=>{setError(t.fail);setLoading(false);});setStats(getStreak('wordle'));return()=>{void audio.current?.close();};},[]);
  useEffect(()=>{if(!game||game.status!=='playing'||paused||startedAt.current===null)return;const id=setInterval(()=>setElapsed(elapsedBase.current+Date.now()-(startedAt.current??Date.now())),250);return()=>clearInterval(id);},[game?.status,paused]);
  useEffect(()=>{const update=()=>setNextMinutes(minutesUntilNextDaily());update();const id=window.setInterval(update,60_000);return()=>window.clearInterval(id);},[]);
  useEffect(()=>{if(!game)return;if(game.status==='playing')storeWordleSave(game,elapsed);else{clearWordleSave();if(!recorded.current&&game.mode==='daily'){recorded.current=true;setStats(recordStreak('wordle',game.status==='won'));}}},[game]);
  useEffect(()=>{if(!game)return;if(game.guesses.length===guessCount.current)return;const grew=game.guesses.length>guessCount.current;guessCount.current=game.guesses.length;if(!grew){setRevealedCols(5);return;}if(reduced){setRevealedCols(5);return;}setRevealedCols(0);let col=0;const id=window.setInterval(()=>{col+=1;setRevealedCols(col);if(col>=5)window.clearInterval(id);},90);return()=>window.clearInterval(id);},[game?.guesses.length,reduced]);
  const pause=useCallback(()=>{if(!game||game.status!=='playing')return;if(paused){startedAt.current=Date.now();setPaused(false);}else{elapsedBase.current=elapsed;startedAt.current=null;setPaused(true);storeWordleSave(game,elapsed);}},[game,paused,elapsed]);
  useEffect(()=>{const hidden=()=>{if(document.hidden&&!paused)pause();};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden);},[pause,paused]);
  const submit=useCallback(()=>{if(!game||paused||!target)return;const reason=explainWordleSubmit(game,target,valid.has(game.current),hard);if(reason){setError(reason==='too-short'?t.short:reason==='invalid'?t.invalid:t.hardFail);tone(160);return;}const next=submitWordle(game,target,true,hard);setError('');setRestored(false);setGame(next);tone(next.status==='won'?880:next.status==='lost'?180:520,next.status==='playing'?.08:.22);},[game,paused,target,valid,hard,t]);
  const key=useCallback((value:string)=>{if(!game||paused||game.status!=='playing')return;if(value==='ENTER'){submit();return;}const normalized=value==='⌫'?'BACKSPACE':value;const next=inputWordle(game,normalized);if(next!==game){setGame(next);setError('');tone(normalized==='BACKSPACE'?240:360,.035);}},[game,paused,submit]);
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.ctrlKey||event.altKey||event.metaKey)return;const value=event.key==='Enter'?'ENTER':event.key==='Backspace'?'BACKSPACE':event.key.toUpperCase();if(value==='ENTER'||value==='BACKSPACE'||/^[A-Z]$/.test(value)){event.preventDefault();key(value);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[key]);
  const evidence=useMemo(()=>{const order={absent:1,present:2,correct:3};const map:Record<string,WordleMark>={};if(!target)return map;for(const guess of game?.guesses??[])evaluateWordleGuess(guess,target).forEach((mark,i)=>{if(!map[guess[i]]||order[mark]>order[map[guess[i]]])map[guess[i]]=mark;});return map;},[game?.guesses,target]);
  const share=async()=>{if(!game||!target)return;const grid=game.guesses.map(g=>evaluateWordleGuess(g,target).map(m=>m==='correct'?'🟩':m==='present'?'🟨':'⬜').join('')).join('\n');try{await navigator.clipboard.writeText(`OIYO Wordle ${game.mode} ${game.status==='won'?game.guesses.length:'X'}/6\n${grid}`);}catch{/* best effort */}};
  if(loading)return <div className="flex min-h-64 flex-col items-center justify-center gap-3"><Spinner className="size-8 text-primary motion-reduce:animate-none"/><p>{t.loading}</p></div>;
  if(!game)return <p role="alert" className="p-6 text-center font-bold text-red-700">{error||t.fail}</p>;
  const display=[...game.guesses,game.current,...Array(Math.max(0,6-game.guesses.length-1)).fill('')].slice(0,6);
  return <div className="not-prose mx-auto flex max-w-lg select-none flex-col items-center gap-4 px-1 py-5">
    <div className="w-full text-center"><h2 className="text-3xl font-black tracking-widest">WORDLE</h2><p className="text-xs font-bold text-muted-foreground">{t.subtitle}</p>{stats&&stats.played>0&&<p className="mt-1 text-xs">{t.streak(stats)}</p>}</div>
    <div className="flex w-full flex-wrap justify-center gap-2"><button type="button" onClick={()=>start('daily')} aria-pressed={game.mode==='daily'} className={`min-h-11 rounded-xl border px-4 text-sm font-bold ${game.mode==='daily'?'bg-primary text-primary-foreground':''}`}>{t.daily}</button><button type="button" onClick={()=>start('random')} aria-pressed={game.mode==='random'} className={`min-h-11 rounded-xl border px-4 text-sm font-bold ${game.mode==='random'?'bg-primary text-primary-foreground':''}`}>{t.random}</button><button type="button" onClick={()=>setHard(v=>!v)} aria-pressed={hard} className={`min-h-11 rounded-xl border px-4 text-sm font-bold ${hard?'bg-primary text-primary-foreground':''}`}>{t.hard}</button><button type="button" onClick={pause} className="min-h-11 rounded-xl border px-3" aria-pressed={paused}>{paused?'▶':'Ⅱ'}<span className="sr-only">{paused?t.resume:t.pause}</span></button><button type="button" onClick={()=>setMuted(v=>!v)} className="min-h-11 rounded-xl border px-3" aria-pressed={muted}>{muted?'🔇':'🔊'}<span className="sr-only">{t.sound}</span></button></div>
    <p className="min-h-5 text-xs font-bold" role="status" aria-live="polite">{restored?t.restored:`${game.mode==='daily'?t.daily:t.random} · ${t.time} ${formatTime(elapsed)}`}</p>
    <div className="grid gap-1.5" role="grid" aria-label="Wordle">{display.map((word,row)=>{const submitted=row<game.guesses.length;const marks=submitted?evaluateWordleGuess(word,target):[];const isLatest=submitted&&row===game.guesses.length-1;return <div key={row} className="flex gap-1.5" role="row">{Array.from({length:5},(_,column)=>{const mark=marks[column];const letter=word[column]??'';const shown=submitted&&(!isLatest||column<revealedCols);return <div key={column} role="gridcell" aria-label={`${letter||'empty'}${shown&&mark?` ${t[mark]}`:''}`} className={`flex h-12 w-12 items-center justify-center rounded-lg border-2 text-xl font-black ${shown&&mark?markClass[mark]:letter?'border-slate-600':'border-slate-300'} ${shown&&isLatest&&column===revealedCols-1&&!reduced?'oiyo-wordle-flip':''}`}>{letter}{shown&&mark&&<span className="ml-0.5 text-[9px]" aria-hidden="true">{markSymbol[mark]}</span>}</div>;})}</div>;})}</div>
    {game.status!=='playing'&&revealedCols>=5&&<div className={`w-full rounded-2xl border-2 p-4 text-center ${game.status==='won'?'border-green-400 bg-green-50':'border-red-300 bg-red-50'}`} role="status" aria-live="assertive"><p className="text-xl font-black">{game.status==='won'?t.won:t.lost(target)}</p><p className="mt-1 text-sm font-bold">{t.attempts} {game.guesses.length}/6 · {t.time} {formatTime(elapsed)}</p>{game.mode==='daily'&&<p className="mt-1 text-xs font-bold text-muted-foreground">{nextCopy(nextMinutes)}</p>}<div className="mt-3 flex justify-center gap-2"><button type="button" onClick={()=>start(game.mode)} className="min-h-11 rounded-xl bg-primary px-4 font-bold text-primary-foreground">{t.again}</button><button type="button" onClick={share} className="min-h-11 rounded-xl border px-4 font-bold">{t.share}</button></div></div>}
    <p id="wordle-error" className="min-h-5 text-sm font-bold text-red-700" role="alert">{error}</p>
    <div className="flex w-full max-w-md flex-col gap-1" aria-label="Keyboard">{ROWS.map((row,i)=><div key={i} className="flex w-full gap-1">{row.map(k=>{const mark=evidence[k];return <button key={k} type="button" onClick={()=>key(k)} disabled={paused||game.status!=='playing'} aria-label={k==='⌫'?'Backspace':k} className={`h-12 min-w-0 rounded-md border text-xs font-black ${k.length>1?'flex-[1.5]':'flex-1'} ${mark?markClass[mark]:'bg-muted/40'} disabled:opacity-50`}>{k}{mark&&<span className="ml-0.5" aria-hidden="true">{markSymbol[mark]}</span>}</button>;})}</div>)}</div><p className="text-center text-xs text-muted-foreground">{t.hint}</p>
  </div>;
}
