import { useMemo, useState } from "react";
import { GameContainer } from "../ui/game/GamePrimitives";
import type { Locale } from "../../lib/i18n";

type CoefficientMethod = "leibniz" | "hoffman";
interface Labels { title: string; subtitle: string; method: string; leibniz: string; hoffman: string; income: string; age: string; retirement: string; rate: string; result: string; months: string; coeff: string; monthlyLoss: string; won: string; warning: string; }
const LABELS: Record<Locale, Labels> = {
  en: { title: "Lost Income Calculator", subtitle: "Present-value estimate using Leibniz or Hoffman coefficients.", method: "Discount method", leibniz: "Leibniz", hoffman: "Hoffman", income: "Monthly income", age: "Current age", retirement: "Working end age", rate: "Labor capacity loss", result: "Estimated lost income", months: "Working months", coeff: "Coefficient", monthlyLoss: "Monthly loss", won: "KRW", warning: "Korean legal-damage estimate only. Disability rate, working period, and court practice can change the result." },
  ko: { title: "일실수입 계산기", subtitle: "라이프니츠식 또는 호프만식 계수로 현재가치를 추정합니다.", method: "계산 방식", leibniz: "라이프니츠", hoffman: "호프만", income: "월 소득", age: "현재 나이", retirement: "가동 종료 나이", rate: "노동능력상실률", result: "일실수입 추정액", months: "가동 개월", coeff: "적용 계수", monthlyLoss: "월 손실", won: "원", warning: "대한민국 손해배상 실무를 단순화한 추정치입니다. 장해율, 가동연한, 법원 판단에 따라 달라질 수 있습니다." },
  ja: { title: "逸失収入計算機", subtitle: "ライプニッツ式またはホフマン式係数で現在価値を推定します。", method: "割引方式", leibniz: "ライプニッツ", hoffman: "ホフマン", income: "月収", age: "現在年齢", retirement: "就労終了年齢", rate: "労働能力喪失率", result: "逸失収入概算", months: "就労月数", coeff: "係数", monthlyLoss: "月間損失", won: "KRW", warning: "韓国法実務向けの簡易推定です。障害率、就労期間、裁判所判断により変わります。" },
  zh: { title: "误工收入损失计算器", subtitle: "使用莱布尼茨或霍夫曼系数估算现值。", method: "折现方式", leibniz: "莱布尼茨", hoffman: "霍夫曼", income: "月收入", age: "当前年龄", retirement: "工作结束年龄", rate: "劳动能力丧失率", result: "收入损失估算", months: "工作月数", coeff: "适用系数", monthlyLoss: "每月损失", won: "韩元", warning: "这是韩国损害赔偿场景的简化估算。伤残率、工作年限和法院判断会改变结果。" },
  fr: { title: "Calculateur de Perte de Revenus", subtitle: "Estimation en valeur actuelle par Leibniz ou Hoffman.", method: "Méthode", leibniz: "Leibniz", hoffman: "Hoffman", income: "Revenu mensuel", age: "Âge actuel", retirement: "Âge de fin d'activité", rate: "Taux de perte", result: "Perte estimée", months: "Mois d'activité", coeff: "Coefficient", monthlyLoss: "Perte mensuelle", won: "KRW", warning: "Estimation simplifiée pour les dommages en Corée. Confirmez les données officielles et juridiques." },
  es: { title: "Calculadora de Pérdida de Ingresos", subtitle: "Estimación de valor presente con coeficientes Leibniz u Hoffman.", method: "Método", leibniz: "Leibniz", hoffman: "Hoffman", income: "Ingreso mensual", age: "Edad actual", retirement: "Edad final laboral", rate: "Pérdida de capacidad", result: "Pérdida estimada", months: "Meses laborales", coeff: "Coeficiente", monthlyLoss: "Pérdida mensual", won: "KRW", warning: "Estimación simplificada para daños en Corea. Confirma criterios oficiales y legales." },
};
function calculateCoefficient(months: number, method: CoefficientMethod): number { const rate = 0.05 / 12; let sum = 0; for (let k = 1; k <= months; k++) sum += method === "leibniz" ? 1 / Math.pow(1 + rate, k) : 1 / (1 + k * rate); if (method === "hoffman" && sum > 240) sum = 240; return sum; }
function formatWon(value: number) { return new Intl.NumberFormat("ko-KR").format(Math.floor(value)); }
export default function LossOfIncomeCalculator({ locale }: { locale: Locale }) {
  const t = LABELS[locale] ?? LABELS.en;
  const [method, setMethod] = useState<CoefficientMethod>("leibniz");
  const [monthlyIncome, setMonthlyIncome] = useState(3000000);
  const [age, setAge] = useState(35);
  const [retirementAge, setRetirementAge] = useState(65);
  const [lossRate, setLossRate] = useState(20);
  const result = useMemo(() => { const months = Math.max(0, (retirementAge - age) * 12); const coefficient = months > 0 ? calculateCoefficient(months, method) : 0; const monthlyLoss = monthlyIncome * (lossRate / 100); const totalLoss = Math.floor(monthlyLoss * coefficient); return { months, coefficient, monthlyLoss, totalLoss }; }, [method, monthlyIncome, age, retirementAge, lossRate]);
  const inputCls = "mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 text-slate-900 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100";
  return <GameContainer title={t.title} subtitle={t.subtitle}><div className="grid gap-4"><div className="grid gap-4 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2"><label className="block"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t.method}</span><select className={inputCls} value={method} onChange={(event) => setMethod(event.target.value as CoefficientMethod)}><option value="leibniz">{t.leibniz}</option><option value="hoffman">{t.hoffman}</option></select></label><label className="block"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t.income}</span><input className={inputCls} type="number" min="0" step="10000" value={monthlyIncome} onChange={(event) => setMonthlyIncome(Number(event.target.value))} /></label><label className="block"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t.age}</span><input className={inputCls} type="number" min="0" value={age} onChange={(event) => setAge(Number(event.target.value))} /></label><label className="block"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t.retirement}</span><input className={inputCls} type="number" min="0" value={retirementAge} onChange={(event) => setRetirementAge(Number(event.target.value))} /></label><label className="block sm:col-span-2"><span className="flex justify-between text-xs font-semibold uppercase tracking-wide text-slate-500"><span>{t.rate}</span><span>{lossRate}%</span></span><input className="mt-3 w-full" type="range" min="0" max="100" step="0.1" value={lossRate} onChange={(event) => setLossRate(Number(event.target.value))} /></label></div><div className="rounded-xl border border-indigo-100 bg-indigo-50 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-indigo-700">{t.result}</p><p className="mt-2 font-mono text-3xl font-black text-indigo-950">{formatWon(result.totalLoss)} {t.won}</p></div><dl className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4"><dt className="text-xs text-slate-500">{t.months}</dt><dd className="mt-1 font-mono font-bold text-slate-900">{result.months}</dd></div><div className="rounded-xl border border-slate-200 bg-white p-4"><dt className="text-xs text-slate-500">{t.coeff}</dt><dd className="mt-1 font-mono font-bold text-slate-900">{result.coefficient.toFixed(4)}</dd></div><div className="rounded-xl border border-slate-200 bg-white p-4"><dt className="text-xs text-slate-500">{t.monthlyLoss}</dt><dd className="mt-1 font-mono font-bold text-slate-900">{formatWon(result.monthlyLoss)} {t.won}</dd></div></dl><p className="rounded-xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-900">{t.warning}</p></div></GameContainer>;
}
