import {describe,it,expect} from 'vitest';
import {createDisaster,respond,advanceDisaster,canRespond,survivors,forecast,type Response} from './disaster-control';
describe('miniature disaster control',()=>{
 it('uses two crews per turn and ignores invalid dispatches',()=>{let s=createDisaster();expect(respond(s,NaN,'fire')).toBe(s);expect(respond(s,1,'fire')).toBe(s);s=respond(s,0,'fire');s=respond(s,3,'drain');expect(s.crews).toBe(0);expect(respond(s,1,'evacuate')).toBe(s);expect(advanceDisaster(s).crews).toBe(2);});
 it('can save every resident in each scenario with prioritized intervention',()=>{for(let seed=0;seed<3;seed++){let s=createDisaster(seed);while(s.phase==='responding'){for(let c=0;c<2;c++){const choices=s.districts.flatMap((d,i)=>([['fire',d.fire*12],['drain',d.water*9],['repair',d.power?0:4]] as const).filter(([a])=>canRespond(s,i,a)).map(([action,value])=>({i,action,value}))).sort((a,b)=>b.value-a.value);if(choices[0])s=respond(s,choices[0].i,choices[0].action as Response);}s=advanceDisaster(s);}expect(s.phase).toBe('stabilized');expect(survivors(s)).toBe(24);expect(s.turn).toBe(8);}});
 it('fails without intervention and freezes the result',()=>{let s=createDisaster();while(s.phase==='responding')s=advanceDisaster(s);expect(s.phase).toBe('failed');expect(advanceDisaster(s)).toBe(s);expect(respond(s,1,'evacuate')).toBe(s);});
 it('evacuates each resident once and preserves the population total',()=>{let s=respond(createDisaster(),0,'evacuate');expect(s.saved).toBe(4);expect(respond(s,0,'evacuate')).toBe(s);for(let i=0;i<8;i++)s=advanceDisaster(s);expect(survivors(s)+s.lost).toBe(24);});
 it('floods cut power and draining precedes effective repair',()=>{let s=advanceDisaster(createDisaster());expect(s.districts[3]!.power).toBe(false);s=respond(s,3,'repair');s=advanceDisaster(s);expect(s.districts[3]!.power).toBe(false);s=respond(respond(s,3,'drain'),3,'repair');s=advanceDisaster(s);expect(s.districts[3]!.power).toBe(true);});
 it('spreads intense fire only to orthogonal neighbors',()=>{let s=createDisaster();s={...s,districts:s.districts.map((d,i)=>({...d,fire:i===2?3:0,water:0}))};s=advanceDisaster(s);expect(s.districts[1]!.fire).toBe(1);expect(s.districts[5]!.fire).toBe(1);expect(s.districts[3]!.fire).toBe(0);});
 it('provides deterministic forecasts and normalizes seeds',()=>{expect(createDisaster(Infinity)).toEqual(createDisaster());expect(forecast(createDisaster())).toEqual({index:2,kind:'fire'});});
});
