import { describe, expect, it } from "vitest"; import { cpuDominoes, createDominoes, dominoCpuReview, dominoEnds, dominoesAnalysis, drawDominoes, passDominoes, playDominoes, replayDominoes, type DominoesState } from "./dominoes";
describe("dominoes match engine", () => {
  it("deals a deterministic 28-tile partition", () => { const a=createDominoes(42), b=createDominoes(42); expect(a).toEqual(b); const ids=[...a.player,...a.cpu,...a.bone,...a.board].map(x=>x.id); expect(ids).toHaveLength(28); expect(new Set(ids).size).toBe(28); });
  it("plays a legal tile immutably and rejects wrong-end plays", () => { const state=createDominoes(12); const ends=dominoEnds(state); const tile=state.player.find(x=>x.a===ends.left||x.b===ends.left||x.a===ends.right||x.b===ends.right)!; const end=tile.a===ends.left||tile.b===ends.left?'left':'right'; const next=playDominoes(state,tile.id,end); expect(next).not.toBe(state); expect(state.player).toHaveLength(7); expect(next.player).toHaveLength(6); expect(next.board).toHaveLength(2); expect(playDominoes(next,tile.id,end)).toBe(next); });
  it("draws only when blocked and passes only with an empty boneyard", () => { const base=createDominoes(1); const blocked:DominoesState={...base,player:[{id:99,a:0,b:0}],bone:[{id:98,a:1,b:1}],board:[{id:97,a:6,b:6}]}; const drawn=drawDominoes(blocked); expect(drawn.player).toHaveLength(2); expect(passDominoes(blocked)).toBe(blocked); const passed=passDominoes({...blocked,bone:[]}); expect(passed.turn).toBe('cpu'); });
  it("finishes a two-pass block by fewest pips", () => { const base=createDominoes(1); const state:DominoesState={...base,player:[{id:90,a:0,b:0}],cpu:[{id:91,a:6,b:6}],bone:[],board:[{id:92,a:5,b:5}],turn:'you',passes:1}; const over=passDominoes(state); expect(over.status).toBe('over'); expect(over.winner).toBe('you'); expect(dominoesAnalysis(over).blocked).toBe(true); });
  it("reviews the deterministic CPU move without changing state", () => { let state=createDominoes(9); while(state.turn==='you'&&state.status==='playing'){const ends=dominoEnds(state),tile=state.player.find(x=>x.a===ends.left||x.b===ends.left||x.a===ends.right||x.b===ends.right);if(tile){state=playDominoes(state,tile.id,tile.a===ends.left||tile.b===ends.left?'left':'right');break}if(state.bone.length)state=drawDominoes(state);else state=passDominoes(state)} const snapshot=structuredClone(state),review=dominoCpuReview(state,3);expect(state).toEqual(snapshot);if(review)expect(review).toMatchObject({tile:expect.any(Object),end:expect.stringMatching(/left|right/),draws:expect.any(Number),reason:expect.any(String)}); });
  it("replays human and deterministic CPU actions", () => { let state=createDominoes(77); const ends=dominoEnds(state); const tile=state.player.find(x=>x.a===ends.left||x.b===ends.left||x.a===ends.right||x.b===ends.right); if(tile) state=playDominoes(state,tile.id,tile.a===ends.left||tile.b===ends.left?'left':'right'); else while(state.bone.length&&!state.player.some(x=>x.a===ends.left||x.b===ends.left||x.a===ends.right||x.b===ends.right)) state=drawDominoes(state); if(state.turn==='cpu') state=cpuDominoes(state,2); expect(replayDominoes(77,2,state.history)).toEqual(state); expect(replayDominoes(77,2,[{kind:'play',tileId:999,end:'left'}])).toBeNull(); });
});
