export type Game2048Direction="up"|"down"|"left"|"right"; export type Game2048Status="playing"|"won"|"over"; export interface Game2048State{board:(number|null)[];score:number;status:Game2048Status;rng:number;moves:number;lastGain:number}
const next=(rng:number)=>{const state=(Math.imul(rng,1664525)+1013904223)>>>0;return{state,value:state/0x1_0000_0000}}; const valid=(v:number|null)=>v===null||(Number.isInteger(v)&&v>=2&&(v&(v-1))===0&&v<=131072);
export function canMove2048(board:readonly(number|null)[]){if(board.length!==16||board.some(v=>!valid(v)))return false;for(let i=0;i<16;i++){if(board[i]===null)return true;if(i%4<3&&board[i]===board[i+1])return true;if(i<12&&board[i]===board[i+4])return true}return false}
function spawn(board:(number|null)[],rng:number){const empty=board.map((v,i)=>v===null?i:-1).filter(i=>i>=0);if(!empty.length)return{board,rng};const a=next(rng),b=next(a.state),out=[...board];out[empty[Math.floor(a.value*empty.length)]]=b.value<.9?2:4;return{board:out,rng:b.state}}
export function createGame2048(seed:number):Game2048State{let board=Array<number|null>(16).fill(null),rng=seed>>>0;let s=spawn(board,rng);s=spawn(s.board,s.rng);return{board:s.board,score:0,status:"playing",rng:s.rng,moves:0,lastGain:0}}
export function restoreGame2048(board:readonly(number|null)[],score:number):Game2048State|null{if(board.length!==16||board.some(v=>!valid(v))||!Number.isInteger(score)||score<0||!canMove2048(board)||board.some(v=>v!==null&&v>=2048))return null;let rng=2166136261;for(const v of board)rng=Math.imul(rng^(v??0),16777619)>>>0;rng=Math.imul(rng^score,16777619)>>>0;return{board:[...board],score,status:"playing",rng,moves:0,lastGain:0}}
const indices=(line:number,dir:Game2048Direction)=>Array.from({length:4},(_,j)=>dir==="left"?line*4+j:dir==="right"?line*4+3-j:dir==="up"?j*4+line:(3-j)*4+line);
export function moveGame2048(state:Game2048State,direction:Game2048Direction):Game2048State{if(state.status!=="playing")return state;const board=Array<number|null>(16).fill(null);let gain=0;for(let line=0;line<4;line++){const ids=indices(line,direction),values=ids.map(i=>state.board[i]).filter((v):v is number=>v!==null),merged:number[]=[];for(let j=0;j<values.length;j++){if(values[j]===values[j+1]){const value=values[j]*2;merged.push(value);gain+=value;j++}else merged.push(values[j])}merged.forEach((value,j)=>board[ids[j]]=value)}if(board.every((v,i)=>v===state.board[i]))return state;const spawned=spawn(board,state.rng),score=state.score+gain,status=spawned.board.some(v=>v!==null&&v>=2048)?"won":canMove2048(spawned.board)?"playing":"over";return{board:spawned.board,score,status,rng:spawned.rng,moves:state.moves+1,lastGain:gain}}
export function game2048Fingerprint(state:Game2048State){return JSON.stringify({board:state.board,score:state.score,status:state.status,rng:state.rng,moves:state.moves,lastGain:state.lastGain})}
export function game2048Analysis(state:Game2048State){const occupied=state.board.filter(Boolean).length,max=Math.max(...state.board.map(v=>v??0));return{max,occupied,empty:16-occupied,moves:state.moves,score:state.score}}
