import { replayJanggi, type JanggiMove, type JanggiState } from "./janggi";
import type { AiLevel, GameMode } from "./ai/types";
export const JANGGI_SAVE_KEY = "oiyo:janggi-state:v1";
export interface JanggiSaveV1 { version: 1; state: JanggiState; mode: GameMode; level: AiLevel; savedAtEpochMs: number }
type StorageLike = Pick<Storage, "getItem" | "setItem" | "removeItem">; const object = (v: unknown): v is Record<string, unknown> => Boolean(v) && typeof v === "object" && !Array.isArray(v); const cell = (v: unknown) => Number.isInteger(v) && (v as number) >= 0 && (v as number) < 10;
const parseMove = (v: unknown): JanggiMove | null => { if (!object(v) || !Array.isArray(v.from) || !Array.isArray(v.to) || v.from.length !== 2 || v.to.length !== 2 || !cell(v.from[0]) || !Number.isInteger(v.from[1]) || (v.from[1] as number) < 0 || (v.from[1] as number) > 8 || !cell(v.to[0]) || !Number.isInteger(v.to[1]) || (v.to[1] as number) < 0 || (v.to[1] as number) > 8) return null; return { from: [v.from[0] as number, v.from[1] as number], to: [v.to[0] as number, v.to[1] as number] }; };
export function parseJanggiSave(raw: string | null, now = Date.now()): JanggiSaveV1 | null { if (!raw || !Number.isFinite(now)) return null; try { const v: unknown = JSON.parse(raw); if (!object(v) || v.version !== 1 || !object(v.state) || !Array.isArray(v.state.history) || v.state.history.length > 500 || !["local", "ai"].includes(v.mode as string) || ![1,2,3].includes(v.level as number) || !Number.isInteger(v.savedAtEpochMs) || (v.savedAtEpochMs as number) > now + 300_000 || now - (v.savedAtEpochMs as number) > 7 * 86_400_000) return null; const history: JanggiMove[] = []; for (const item of v.state.history) { const move = parseMove(item); if (!move) return null; history.push(move); } const state = replayJanggi(history); if (!state || state.status !== "playing" || JSON.stringify(state) !== JSON.stringify(v.state)) return null; return { version: 1, state, mode: v.mode as GameMode, level: v.level as AiLevel, savedAtEpochMs: v.savedAtEpochMs as number }; } catch { return null; } }
export function loadJanggiSave(now = Date.now(), storage: StorageLike | undefined = typeof localStorage === "undefined" ? undefined : localStorage) { try { return storage ? parseJanggiSave(storage.getItem(JANGGI_SAVE_KEY), now) : null; } catch { return null; } }
export function storeJanggiSave(state: JanggiState, mode: GameMode, level: AiLevel, savedAtEpochMs = Date.now(), storage: StorageLike | undefined = typeof localStorage === "undefined" ? undefined : localStorage): void { if (!storage || state.status !== "playing" || state.moves === 0) return; try { storage.setItem(JANGGI_SAVE_KEY, JSON.stringify({ version: 1, state, mode, level, savedAtEpochMs })); } catch { /* best effort */ } }
export function clearJanggiSave(storage: StorageLike | undefined = typeof localStorage === "undefined" ? undefined : localStorage): void { try { storage?.removeItem(JANGGI_SAVE_KEY); } catch { /* best effort */ } }
