import {describe,it,expect} from 'vitest';
import {createOrbitGarden,plantOrbit,launchOrbit,stepOrbit,orbitClearance,orbitRadius} from './orbit-gardener';
describe('orbit gardener',()=>{
 it('sustains all three missions with two flowers on each planet',()=>{for(let mission=0;mission<3;mission++){let s=createOrbitGarden(mission);for(let p=0;p<3;p++)s=plantOrbit(plantOrbit(s,p,1),p,1);expect(orbitClearance(s)).toBeGreaterThan(0);s=launchOrbit(s);while(s.phase==='running')s=stepOrbit(s);expect(s.phase).toBe('balanced');expect(s.day).toBe(s.target);expect(s.planets.every(p=>p.health===100)).toBe(true);expect(stepOrbit(s)).toBe(s);}});
 it('detects a later collision between initially separated planets',()=>{let s=createOrbitGarden();for(const [p,n] of [[0,2],[1,7],[2,2]] as const)for(let i=0;i<n;i++)s=plantOrbit(s,p,1);s={...s,planets:s.planets.map((p,i)=>({...p,angle:i===1?.5:0}))};s=launchOrbit(s);expect(s.phase).toBe('running');while(s.phase==='running')s=stepOrbit(s);expect(s.phase).toBe('collision');expect(s.day).toBe(28);});
 it('withers an underplanted ecosystem and stops simulation',()=>{let s=launchOrbit(createOrbitGarden());for(let i=0;i<40;i++)s=stepOrbit(s);expect(s.phase).toBe('withered');expect(s.day).toBe(20);});
 it('detects an overcrowded orbit at launch',()=>{let s=createOrbitGarden();for(let i=0;i<8;i++)s=plantOrbit(s,1,1);expect(orbitClearance(s)).toBeLessThan(0);expect(launchOrbit(s).phase).toBe('collision');});
 it('conserves seeds on pruning and rejects invalid or exhausted planting',()=>{let s=createOrbitGarden(2);const original=s;expect(plantOrbit(s,NaN,1)).toBe(s);expect(plantOrbit(s,0,-1)).toBe(s);s=plantOrbit(plantOrbit(s,0,1),0,-1);expect(s).toEqual(original);for(let i=0;i<8;i++)s=plantOrbit(s,0,1);expect(s.seeds).toBe(0);expect(plantOrbit(s,1,1)).toBe(s);expect(orbitRadius(s.planets[0]!)).toBe(32);});
 it('prevents changing plants during an expedition and normalizes mission input',()=>{const s=launchOrbit(createOrbitGarden());expect(plantOrbit(s,0,1)).toBe(s);expect(launchOrbit(s)).toBe(s);expect(createOrbitGarden(NaN)).toEqual(createOrbitGarden());});
 it('replays identical daily positions without mutating the starting state',()=>{const initial=createOrbitGarden();const a=stepOrbit(launchOrbit(initial)),b=stepOrbit(launchOrbit(initial));expect(a).toEqual(b);expect(initial.day).toBe(0);expect(initial.planets[0]!.angle).toBe(0);});
});
