import {describe,it,expect} from 'vitest';
import {createWhaleCity,moveWhaleBuilding,braceWhaleBuilding,sootheWhale,advanceWhale,floodedSlots,whalePeople,whaleTilt,seaForecast,whaleScore} from './whale-city';
describe('city on a whale',()=>{
 it('finishes all voyages by moving homes to the ridge and protecting forecast waves',()=>{for(let mission=0;mission<3;mission++){let s=createWhaleCity(mission);s=moveWhaleBuilding(s,0,3);s=moveWhaleBuilding(s,2,5);while(s.phase==='sailing'){for(const b of s.buildings)if(b.health>0&&floodedSlots(s).includes(b.slot))s=braceWhaleBuilding(s,b.id);while(s.actions>0&&s.fatigue>0)s=sootheWhale(s);s=advanceWhale(s);}expect(s.phase).toBe('arrived');expect(whalePeople(s)).toBe(12);expect(s.turn).toBe(12);expect(whaleScore(s)).toBeGreaterThan(500);expect(advanceWhale(s)).toBe(s);}});
 it('fails an unmanaged voyage and locks terminal actions',()=>{let s=createWhaleCity();while(s.phase==='sailing')s=advanceWhale(s);expect(s.phase).toBe('lost');expect(moveWhaleBuilding(s,0,3)).toBe(s);expect(sootheWhale(s)).toBe(s);});
 it('rejects occupied, fractional, invalid and exhausted moves without changing state',()=>{let s=createWhaleCity();expect(moveWhaleBuilding(s,0,4)).toBe(s);expect(moveWhaleBuilding(s,0,NaN)).toBe(s);expect(moveWhaleBuilding(s,0,1.5)).toBe(s);s=moveWhaleBuilding(moveWhaleBuilding(s,0,3),2,5);expect(moveWhaleBuilding(s,3,1)).toBe(s);expect(s.actions).toBe(0);});
 it('protection lasts one wave and cannot be stacked',()=>{let s=advanceWhale(createWhaleCity());expect(seaForecast(s)).toBe('left');s=braceWhaleBuilding(s,0);expect(braceWhaleBuilding(s,0)).toBe(s);s=advanceWhale(s);expect(s.buildings[0]!.health).toBe(3);expect(s.buildings[0]!.braced).toBe(false);s=advanceWhale(s);expect(s.buildings[0]!.health).toBe(2);});
 it('breathing restores fatigue while asymmetric mass increases it',()=>{const s=createWhaleCity();expect(whaleTilt(s)).toBe(1);const n=advanceWhale(s);expect(n.fatigue).toBeLessThan(s.fatigue);const off=moveWhaleBuilding(s,1,5);expect(whaleTilt(off)).toBe(3);expect(advanceWhale(off).fatigue).toBeGreaterThan(n.fatigue);});
 it('deep water threatens ridge edges only in the third voyage',()=>{const a={...createWhaleCity(),turn:2},b={...createWhaleCity(2),turn:2};expect(floodedSlots(a)).not.toContain(3);expect(floodedSlots(b)).toContain(3);expect(floodedSlots(b)).not.toContain(4);});
 it('normalizes missions and keeps simulations deterministic and immutable',()=>{const s=createWhaleCity();expect(createWhaleCity(NaN)).toEqual(s);expect(advanceWhale(s)).toEqual(advanceWhale(s));expect(s.turn).toBe(0);});
});
