import * as THREE from 'three';
import {floodedSlots,seaForecast,whaleTilt,type WhaleCity} from './whale-city';
export function mountWhaleScene(canvas:HTMLCanvasElement){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-6,6,5,-5,.1,100);camera.position.set(8,9,11);camera.lookAt(0,0,0);
 scene.add(new THREE.HemisphereLight(0xe4ffff,0x244652,3));const sun=new THREE.DirectionalLight(0xffdfb0,3);sun.position.set(-4,8,4);scene.add(sun);
 const body=new THREE.Group();scene.add(body);const dynamic=new THREE.Group();body.add(dynamic);
 const geo=new THREE.SphereGeometry(1,40,24);const blue=new THREE.MeshStandardMaterial({color:0x356c80,roughness:.45}),belly=new THREE.MeshStandardMaterial({color:0x91b4b1,roughness:.7});
 function ellipsoid(x:number,y:number,z:number,sx:number,sy:number,sz:number,mat:THREE.Material){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);body.add(m);return m;}
 ellipsoid(0,-.4,0,1.85,.8,3.6,blue);ellipsoid(0,-.8,-.4,1.5,.45,2.8,belly);ellipsoid(0,-.1,-2.3,1.7,.7,1.4,blue);
 for(const side of [-1,1]){const fin=ellipsoid(side*1.7,-.55,.2,1.3,.12,.6,blue);fin.rotation.y=side*.5;const tail=ellipsoid(side*.8,-.15,3.8,1.2,.14,.55,blue);tail.rotation.z=side*.18;ellipsoid(side*1.48,-.07,-2.65,.09,.09,.09,new THREE.MeshStandardMaterial({color:0x142e3a}));}
 const sea=new THREE.Mesh(new THREE.CircleGeometry(6,64),new THREE.MeshStandardMaterial({color:0x74b4b3,transparent:true,opacity:.2,roughness:.15}));sea.rotation.x=-Math.PI/2;sea.position.y=-.8;scene.add(sea);
 let latest:WhaleCity|undefined,selected=0,disposed=false;
 function clear(){while(dynamic.children.length){const o=dynamic.children[0]!;dynamic.remove(o);o.traverse(child=>{if(child instanceof THREE.Mesh){child.geometry.dispose();const mats=Array.isArray(child.material)?child.material:[child.material];mats.forEach(m=>m.dispose());}});}}
 function render(){if(disposed)return;const width=canvas.clientWidth,height=canvas.clientHeight;if(!width||!height)return;renderer.setSize(width,height,false);const aspect=width/height;camera.left=-5*aspect;camera.right=5*aspect;camera.updateProjectionMatrix();renderer.render(scene,camera);}
 function update(s:WhaleCity,id:number){latest=s;selected=id;clear();const wet=floodedSlots(s);body.rotation.z=Math.max(-.16,Math.min(.16,-whaleTilt(s)*.025));body.position.y=seaForecast(s)==='dive'?-.18:0;
 for(let slot=0;slot<9;slot++){const x=(slot%3-1)*.92,z=(Math.floor(slot/3)-1)*1.12;const floor=new THREE.Mesh(new THREE.BoxGeometry(.84,.09,1.02),new THREE.MeshStandardMaterial({color:wet.includes(slot)?0x76becb:0xd6d6ad,transparent:true,opacity:.8}));floor.position.set(x,.43,z);dynamic.add(floor);const b=s.buildings.find(b=>b.slot===slot&&b.health>0);if(!b)continue;const mat=new THREE.MeshStandardMaterial({color:b.id===selected?0xffdc86:b.id===3?0x799766:0xf0e5ce});const house=new THREE.Mesh(new THREE.BoxGeometry(.52,b.id===3?.13:.5,.62),mat);house.position.set(x,b.id===3?.54:.74,z);dynamic.add(house);if(b.id!==3){const roof=new THREE.Mesh(new THREE.ConeGeometry(.49,.3,4),new THREE.MeshStandardMaterial({color:b.health<2?0x865b4a:0xa85d45}));roof.rotation.y=Math.PI/4;roof.position.set(x,1.14,z);dynamic.add(roof);}else{for(let n=0;n<3;n++){const shrub=new THREE.Mesh(new THREE.SphereGeometry(.15,10,8),new THREE.MeshStandardMaterial({color:0x98b276}));shrub.position.set(x+(n-1)*.17,.7,z);dynamic.add(shrub);}}if(b.braced){const ring=new THREE.Mesh(new THREE.TorusGeometry(.4,.035,6,32),new THREE.MeshStandardMaterial({color:0xf2d996}));ring.rotation.x=Math.PI/2;ring.position.set(x,.52,z);dynamic.add(ring);}}
 render();}
 const observer=new ResizeObserver(render);observer.observe(canvas);const lost=(e:Event)=>{e.preventDefault();canvas.hidden=true;};canvas.addEventListener('webglcontextlost',lost);const restored=()=>{canvas.hidden=false;if(latest)update(latest,selected);};canvas.addEventListener('webglcontextrestored',restored);
 return {update,dispose(){disposed=true;observer.disconnect();clear();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});renderer.dispose();canvas.removeEventListener('webglcontextlost',lost);canvas.removeEventListener('webglcontextrestored',restored);}};
}
